// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity.proto

package com_salty_protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BasicReq_Language int32

const (
	BasicReq_CHINESE BasicReq_Language = 0
	BasicReq_ENGLISH BasicReq_Language = 1
)

var BasicReq_Language_name = map[int32]string{
	0: "CHINESE",
	1: "ENGLISH",
}

var BasicReq_Language_value = map[string]int32{
	"CHINESE": 0,
	"ENGLISH": 1,
}

func (x BasicReq_Language) String() string {
	return proto.EnumName(BasicReq_Language_name, int32(x))
}

func (BasicReq_Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0, 0}
}

type BasicReq_OS int32

const (
	BasicReq_UNKNOWN BasicReq_OS = 0
	BasicReq_ANDROID BasicReq_OS = 1
	BasicReq_IOS     BasicReq_OS = 2
	BasicReq_WINDOWS BasicReq_OS = 3
)

var BasicReq_OS_name = map[int32]string{
	0: "UNKNOWN",
	1: "ANDROID",
	2: "IOS",
	3: "WINDOWS",
}

var BasicReq_OS_value = map[string]int32{
	"UNKNOWN": 0,
	"ANDROID": 1,
	"IOS":     2,
	"WINDOWS": 3,
}

func (x BasicReq_OS) String() string {
	return proto.EnumName(BasicReq_OS_name, int32(x))
}

func (BasicReq_OS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0, 1}
}

type UserProfile_Sex int32

const (
	UserProfile_NOT_SET UserProfile_Sex = 0
	UserProfile_MALE    UserProfile_Sex = 1
	UserProfile_FEMALE  UserProfile_Sex = 2
)

var UserProfile_Sex_name = map[int32]string{
	0: "NOT_SET",
	1: "MALE",
	2: "FEMALE",
}

var UserProfile_Sex_value = map[string]int32{
	"NOT_SET": 0,
	"MALE":    1,
	"FEMALE":  2,
}

func (x UserProfile_Sex) String() string {
	return proto.EnumName(UserProfile_Sex_name, int32(x))
}

func (UserProfile_Sex) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{2, 0}
}

type RegisterReq_RegisterType int32

const (
	RegisterReq_TELEPHONE RegisterReq_RegisterType = 0
	RegisterReq_EMAIL     RegisterReq_RegisterType = 1
)

var RegisterReq_RegisterType_name = map[int32]string{
	0: "TELEPHONE",
	1: "EMAIL",
}

var RegisterReq_RegisterType_value = map[string]int32{
	"TELEPHONE": 0,
	"EMAIL":     1,
}

func (x RegisterReq_RegisterType) String() string {
	return proto.EnumName(RegisterReq_RegisterType_name, int32(x))
}

func (RegisterReq_RegisterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{3, 0}
}

type SMSReq_CodeType int32

const (
	SMSReq_REGISTER SMSReq_CodeType = 0
	SMSReq_LOGIN    SMSReq_CodeType = 1
)

var SMSReq_CodeType_name = map[int32]string{
	0: "REGISTER",
	1: "LOGIN",
}

var SMSReq_CodeType_value = map[string]int32{
	"REGISTER": 0,
	"LOGIN":    1,
}

func (x SMSReq_CodeType) String() string {
	return proto.EnumName(SMSReq_CodeType_name, int32(x))
}

func (SMSReq_CodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{5, 0}
}

// Basic Request
type BasicReq struct {
	DeviceID             string            `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Language             BasicReq_Language `protobuf:"varint,3,opt,name=language,proto3,enum=com.salty.protos.BasicReq_Language" json:"language,omitempty"`
	Os                   BasicReq_OS       `protobuf:"varint,4,opt,name=os,proto3,enum=com.salty.protos.BasicReq_OS" json:"os,omitempty"`
	Token                string            `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Data                 *any.Any          `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BasicReq) Reset()         { *m = BasicReq{} }
func (m *BasicReq) String() string { return proto.CompactTextString(m) }
func (*BasicReq) ProtoMessage()    {}
func (*BasicReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0}
}

func (m *BasicReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicReq.Unmarshal(m, b)
}
func (m *BasicReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicReq.Marshal(b, m, deterministic)
}
func (m *BasicReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicReq.Merge(m, src)
}
func (m *BasicReq) XXX_Size() int {
	return xxx_messageInfo_BasicReq.Size(m)
}
func (m *BasicReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicReq.DiscardUnknown(m)
}

var xxx_messageInfo_BasicReq proto.InternalMessageInfo

func (m *BasicReq) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *BasicReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *BasicReq) GetLanguage() BasicReq_Language {
	if m != nil {
		return m.Language
	}
	return BasicReq_CHINESE
}

func (m *BasicReq) GetOs() BasicReq_OS {
	if m != nil {
		return m.Os
	}
	return BasicReq_UNKNOWN
}

func (m *BasicReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *BasicReq) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

// Basic Response
type BasicResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *any.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicResp) Reset()         { *m = BasicResp{} }
func (m *BasicResp) String() string { return proto.CompactTextString(m) }
func (*BasicResp) ProtoMessage()    {}
func (*BasicResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{1}
}

func (m *BasicResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicResp.Unmarshal(m, b)
}
func (m *BasicResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicResp.Marshal(b, m, deterministic)
}
func (m *BasicResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicResp.Merge(m, src)
}
func (m *BasicResp) XXX_Size() int {
	return xxx_messageInfo_BasicResp.Size(m)
}
func (m *BasicResp) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicResp.DiscardUnknown(m)
}

var xxx_messageInfo_BasicResp proto.InternalMessageInfo

func (m *BasicResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BasicResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *BasicResp) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserProfile struct {
	UserID               string               `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Telephone            string               `protobuf:"bytes,2,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username             string               `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Nickname             string               `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string               `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description          string               `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Sex                  UserProfile_Sex      `protobuf:"varint,8,opt,name=sex,proto3,enum=com.salty.protos.UserProfile_Sex" json:"sex,omitempty"`
	Birthday             *timestamp.Timestamp `protobuf:"bytes,9,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Location             string               `protobuf:"bytes,10,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{2}
}

func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfile.Unmarshal(m, b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
}
func (m *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(m, src)
}
func (m *UserProfile) XXX_Size() int {
	return xxx_messageInfo_UserProfile.Size(m)
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UserProfile) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *UserProfile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserProfile) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserProfile) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserProfile) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserProfile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UserProfile) GetSex() UserProfile_Sex {
	if m != nil {
		return m.Sex
	}
	return UserProfile_NOT_SET
}

func (m *UserProfile) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *UserProfile) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type RegisterReq struct {
	RegisterType         RegisterReq_RegisterType `protobuf:"varint,1,opt,name=registerType,proto3,enum=com.salty.protos.RegisterReq_RegisterType" json:"registerType,omitempty"`
	Password             string                   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	VerificationCode     string                   `protobuf:"bytes,3,opt,name=verificationCode,proto3" json:"verificationCode,omitempty"`
	UserProfile          *UserProfile             `protobuf:"bytes,4,opt,name=userProfile,proto3" json:"userProfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{3}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetRegisterType() RegisterReq_RegisterType {
	if m != nil {
		return m.RegisterType
	}
	return RegisterReq_TELEPHONE
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

func (m *RegisterReq) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type RegisterResp struct {
	Profile              *UserProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{4}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetProfile() *UserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type SMSReq struct {
	CodeType SMSReq_CodeType `protobuf:"varint,1,opt,name=codeType,proto3,enum=com.salty.protos.SMSReq_CodeType" json:"codeType,omitempty"`
	// Types that are valid to be assigned to TargetAccount:
	//	*SMSReq_Telephone
	//	*SMSReq_Email
	TargetAccount        isSMSReq_TargetAccount `protobuf_oneof:"targetAccount"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SMSReq) Reset()         { *m = SMSReq{} }
func (m *SMSReq) String() string { return proto.CompactTextString(m) }
func (*SMSReq) ProtoMessage()    {}
func (*SMSReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{5}
}

func (m *SMSReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSReq.Unmarshal(m, b)
}
func (m *SMSReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSReq.Marshal(b, m, deterministic)
}
func (m *SMSReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSReq.Merge(m, src)
}
func (m *SMSReq) XXX_Size() int {
	return xxx_messageInfo_SMSReq.Size(m)
}
func (m *SMSReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSReq.DiscardUnknown(m)
}

var xxx_messageInfo_SMSReq proto.InternalMessageInfo

func (m *SMSReq) GetCodeType() SMSReq_CodeType {
	if m != nil {
		return m.CodeType
	}
	return SMSReq_REGISTER
}

type isSMSReq_TargetAccount interface {
	isSMSReq_TargetAccount()
}

type SMSReq_Telephone struct {
	Telephone string `protobuf:"bytes,2,opt,name=telephone,proto3,oneof"`
}

type SMSReq_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

func (*SMSReq_Telephone) isSMSReq_TargetAccount() {}

func (*SMSReq_Email) isSMSReq_TargetAccount() {}

func (m *SMSReq) GetTargetAccount() isSMSReq_TargetAccount {
	if m != nil {
		return m.TargetAccount
	}
	return nil
}

func (m *SMSReq) GetTelephone() string {
	if x, ok := m.GetTargetAccount().(*SMSReq_Telephone); ok {
		return x.Telephone
	}
	return ""
}

func (m *SMSReq) GetEmail() string {
	if x, ok := m.GetTargetAccount().(*SMSReq_Email); ok {
		return x.Email
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SMSReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SMSReq_Telephone)(nil),
		(*SMSReq_Email)(nil),
	}
}

type SMSResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSResp) Reset()         { *m = SMSResp{} }
func (m *SMSResp) String() string { return proto.CompactTextString(m) }
func (*SMSResp) ProtoMessage()    {}
func (*SMSResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{6}
}

func (m *SMSResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSResp.Unmarshal(m, b)
}
func (m *SMSResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSResp.Marshal(b, m, deterministic)
}
func (m *SMSResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSResp.Merge(m, src)
}
func (m *SMSResp) XXX_Size() int {
	return xxx_messageInfo_SMSResp.Size(m)
}
func (m *SMSResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSResp.DiscardUnknown(m)
}

var xxx_messageInfo_SMSResp proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("com.salty.protos.BasicReq_Language", BasicReq_Language_name, BasicReq_Language_value)
	proto.RegisterEnum("com.salty.protos.BasicReq_OS", BasicReq_OS_name, BasicReq_OS_value)
	proto.RegisterEnum("com.salty.protos.UserProfile_Sex", UserProfile_Sex_name, UserProfile_Sex_value)
	proto.RegisterEnum("com.salty.protos.RegisterReq_RegisterType", RegisterReq_RegisterType_name, RegisterReq_RegisterType_value)
	proto.RegisterEnum("com.salty.protos.SMSReq_CodeType", SMSReq_CodeType_name, SMSReq_CodeType_value)
	proto.RegisterType((*BasicReq)(nil), "com.salty.protos.BasicReq")
	proto.RegisterType((*BasicResp)(nil), "com.salty.protos.BasicResp")
	proto.RegisterType((*UserProfile)(nil), "com.salty.protos.UserProfile")
	proto.RegisterType((*RegisterReq)(nil), "com.salty.protos.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "com.salty.protos.RegisterResp")
	proto.RegisterType((*SMSReq)(nil), "com.salty.protos.SMSReq")
	proto.RegisterType((*SMSResp)(nil), "com.salty.protos.SMSResp")
}

func init() { proto.RegisterFile("entity.proto", fileDescriptor_cf50d946d740d100) }

var fileDescriptor_cf50d946d740d100 = []byte{
	// 736 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xdb, 0x4e, 0xe3, 0x48,
	0x10, 0x8d, 0x9d, 0x9b, 0x5d, 0x09, 0xac, 0xd5, 0x42, 0xc8, 0x1b, 0xed, 0x25, 0x6b, 0xf6, 0x21,
	0x42, 0x5a, 0x23, 0xc1, 0x6a, 0xf7, 0x69, 0x85, 0x02, 0xf1, 0x26, 0xd6, 0x06, 0x1b, 0xb5, 0x83,
	0x78, 0x5c, 0x35, 0x4e, 0x13, 0x2c, 0x12, 0xdb, 0xe3, 0x76, 0x32, 0xe4, 0x2f, 0xe6, 0x67, 0xe6,
	0x2f, 0xe6, 0x9b, 0x46, 0xa3, 0x6e, 0x5f, 0x30, 0x04, 0xcd, 0xcc, 0x9b, 0x4f, 0x75, 0x95, 0xeb,
	0xd4, 0x39, 0x55, 0xd0, 0xa5, 0x61, 0x1a, 0xa4, 0x5b, 0x33, 0x4e, 0xa2, 0x34, 0x42, 0x9a, 0x1f,
	0xad, 0x4c, 0x46, 0x96, 0x45, 0x80, 0xf5, 0x7e, 0x5d, 0x44, 0xd1, 0x62, 0x49, 0x4f, 0x04, 0xbc,
	0x5b, 0xdf, 0x9f, 0xa4, 0xc1, 0x8a, 0xb2, 0x94, 0xac, 0xe2, 0x2c, 0xa3, 0xf7, 0xe3, 0xeb, 0x04,
	0x12, 0xe6, 0xc5, 0xc6, 0x27, 0x19, 0x94, 0x0b, 0xc2, 0x02, 0x1f, 0xd3, 0x77, 0xa8, 0x07, 0xca,
	0x9c, 0x6e, 0x02, 0x9f, 0xda, 0x23, 0x5d, 0xea, 0x4b, 0x03, 0x15, 0x97, 0x18, 0xe9, 0xd0, 0xde,
	0xd0, 0x84, 0x05, 0x51, 0xa8, 0xcb, 0xe2, 0xa9, 0x80, 0xe8, 0x1c, 0x94, 0x25, 0x09, 0x17, 0x6b,
	0xb2, 0xa0, 0x7a, 0xbd, 0x2f, 0x0d, 0xf6, 0x4f, 0x8f, 0xcc, 0xd7, 0x1c, 0xcd, 0xa2, 0x87, 0x39,
	0xcd, 0x53, 0x71, 0x59, 0x84, 0xfe, 0x00, 0x39, 0x62, 0x7a, 0x43, 0x94, 0xfe, 0xfc, 0x95, 0x52,
	0xd7, 0xc3, 0x72, 0xc4, 0xd0, 0x01, 0x34, 0xd3, 0xe8, 0x91, 0x86, 0x7a, 0x53, 0xf0, 0xc8, 0x00,
	0x1a, 0x40, 0x63, 0x4e, 0x52, 0xa2, 0xb7, 0xfa, 0xd2, 0xa0, 0x73, 0x7a, 0x60, 0x66, 0x23, 0x9b,
	0xc5, 0xc8, 0xe6, 0x30, 0xdc, 0x62, 0x91, 0x61, 0xfc, 0x0e, 0x4a, 0x41, 0x02, 0x75, 0xa0, 0x7d,
	0x39, 0xb1, 0x1d, 0xcb, 0xb3, 0xb4, 0x1a, 0x07, 0x96, 0x33, 0x9e, 0xda, 0xde, 0x44, 0x93, 0x8c,
	0x3f, 0x41, 0x76, 0x3d, 0x1e, 0xba, 0x71, 0xfe, 0x73, 0xdc, 0x5b, 0x27, 0x7b, 0x1f, 0x3a, 0x23,
	0xec, 0xda, 0x23, 0x4d, 0x42, 0x6d, 0xa8, 0xdb, 0xae, 0xa7, 0xc9, 0x3c, 0x7a, 0x6b, 0x3b, 0x23,
	0xf7, 0xd6, 0xd3, 0xea, 0x86, 0x0f, 0x6a, 0x4e, 0x97, 0xc5, 0x08, 0x41, 0xc3, 0x8f, 0xe6, 0x54,
	0x48, 0xd9, 0xc4, 0xe2, 0x9b, 0xcb, 0xb8, 0xa2, 0x8c, 0x71, 0xad, 0x72, 0x19, 0x73, 0x58, 0x0e,
	0x50, 0xff, 0xe6, 0x00, 0x9f, 0x65, 0xe8, 0xdc, 0x30, 0x9a, 0x5c, 0x27, 0xd1, 0x7d, 0xb0, 0xa4,
	0xe8, 0x10, 0x5a, 0x6b, 0x46, 0x93, 0xd2, 0xb4, 0x1c, 0xa1, 0x9f, 0x40, 0x4d, 0xe9, 0x92, 0xc6,
	0x0f, 0x51, 0x58, 0x74, 0x7b, 0x0e, 0x70, 0x19, 0xe9, 0x8a, 0x04, 0x4b, 0xd1, 0x50, 0xc5, 0x19,
	0xe0, 0x2b, 0xc0, 0xab, 0x43, 0xb2, 0xa2, 0xc2, 0x11, 0x15, 0x97, 0x98, 0xbf, 0x85, 0x81, 0xff,
	0x28, 0xde, 0x32, 0xed, 0x4b, 0xcc, 0x39, 0x90, 0x0d, 0x49, 0x49, 0x22, 0x0c, 0x50, 0x71, 0x8e,
	0x50, 0x1f, 0x3a, 0x73, 0xca, 0xfc, 0x24, 0x88, 0x53, 0xbe, 0x3a, 0x6d, 0xf1, 0x58, 0x0d, 0xa1,
	0x33, 0xa8, 0x33, 0xfa, 0xa4, 0x2b, 0xc2, 0xfe, 0xdf, 0x76, 0xed, 0xaf, 0x4c, 0x6a, 0x7a, 0xf4,
	0x09, 0xf3, 0x6c, 0xf4, 0x17, 0x28, 0x77, 0x41, 0x92, 0x3e, 0xcc, 0xc9, 0x56, 0x57, 0x85, 0x60,
	0xbd, 0x1d, 0xc1, 0x66, 0xc5, 0x15, 0xe0, 0x32, 0x97, 0x8f, 0xb0, 0x8c, 0x7c, 0x22, 0xb8, 0x40,
	0x36, 0x42, 0x81, 0x8d, 0x01, 0xd4, 0x3d, 0xfa, 0xc4, 0xfd, 0x74, 0xdc, 0xd9, 0xff, 0x9e, 0x35,
	0xd3, 0x6a, 0x48, 0x81, 0xc6, 0xd5, 0x70, 0x6a, 0x69, 0x12, 0x02, 0x68, 0xfd, 0x6b, 0x89, 0x6f,
	0xd9, 0xf8, 0x20, 0x43, 0x07, 0xd3, 0x45, 0xc0, 0x52, 0x9a, 0xf0, 0xbb, 0x71, 0xa0, 0x9b, 0xe4,
	0x70, 0xb6, 0x8d, 0x33, 0xc3, 0xf7, 0x4f, 0x8f, 0x77, 0x67, 0xa9, 0x14, 0x95, 0xdf, 0xbc, 0x02,
	0xbf, 0xa8, 0xe7, 0x2c, 0x63, 0xc2, 0xd8, 0xfb, 0x28, 0x99, 0xe7, 0xbe, 0x95, 0x18, 0x1d, 0x83,
	0xb6, 0xa1, 0x49, 0x70, 0x1f, 0x64, 0xac, 0x2f, 0xf9, 0x82, 0x65, 0x0e, 0xee, 0xc4, 0xd1, 0x39,
	0x74, 0xd6, 0xcf, 0xea, 0x09, 0x3f, 0x3b, 0x6f, 0x5d, 0x58, 0x45, 0x62, 0x5c, 0xad, 0x30, 0x06,
	0xd0, 0xad, 0xd2, 0x44, 0x7b, 0xa0, 0xce, 0xac, 0xa9, 0x75, 0x3d, 0x71, 0x1d, 0x7e, 0x30, 0x2a,
	0x34, 0xad, 0xab, 0xa1, 0x3d, 0xd5, 0x24, 0x63, 0xfc, 0x9c, 0x29, 0x76, 0xff, 0x6f, 0x68, 0xc7,
	0x79, 0x5b, 0xe9, 0x7b, 0xda, 0x16, 0xd9, 0xc6, 0x47, 0x09, 0x5a, 0xde, 0x95, 0xc7, 0x65, 0xfd,
	0x07, 0x14, 0x7e, 0x33, 0x15, 0x49, 0xdf, 0x58, 0x8f, 0x2c, 0xd7, 0xbc, 0xcc, 0x13, 0x71, 0x59,
	0x82, 0x7e, 0xd9, 0x59, 0xff, 0x49, 0xad, 0x7a, 0x00, 0x87, 0x2f, 0x0e, 0x60, 0x52, 0xcb, 0x4f,
	0xc0, 0x38, 0x02, 0xa5, 0xf8, 0x1b, 0xea, 0x82, 0x82, 0xad, 0xb1, 0xed, 0xcd, 0x2c, 0x9c, 0xcd,
	0x3b, 0x75, 0xc7, 0xb6, 0xa3, 0x49, 0x17, 0x3f, 0xc0, 0x5e, 0x4a, 0x92, 0x05, 0x4d, 0x87, 0xbe,
	0x1f, 0xad, 0xc3, 0xd4, 0x50, 0xa1, 0x2d, 0xa8, 0xb0, 0xf8, 0x42, 0xbe, 0x96, 0xee, 0x5a, 0x82,
	0xde, 0xd9, 0x97, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xe2, 0xdd, 0x31, 0xbc, 0x05, 0x00, 0x00,
}
