// Code generated by protoc-gen-go. DO NOT EDIT.
// source: salty.proto

package com_salty_protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CodeType int32

const (
	CodeType_REGISTER CodeType = 0
	CodeType_LOGIN    CodeType = 1
)

var CodeType_name = map[int32]string{
	0: "REGISTER",
	1: "LOGIN",
}

var CodeType_value = map[string]int32{
	"REGISTER": 0,
	"LOGIN":    1,
}

func (x CodeType) String() string {
	return proto.EnumName(CodeType_name, int32(x))
}

func (CodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f0b0587afcdc51fc, []int{0}
}

type Role int32

const (
	Role_DEFAULT     Role = 0
	Role_ADMIN       Role = 10
	Role_SUPER_ADMIN Role = 99
)

var Role_name = map[int32]string{
	0:  "DEFAULT",
	10: "ADMIN",
	99: "SUPER_ADMIN",
}

var Role_value = map[string]int32{
	"DEFAULT":     0,
	"ADMIN":       10,
	"SUPER_ADMIN": 99,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f0b0587afcdc51fc, []int{1}
}

type Sex int32

const (
	Sex_MALE   Sex = 0
	Sex_FEMALE Sex = 1
)

var Sex_name = map[int32]string{
	0: "MALE",
	1: "FEMALE",
}

var Sex_value = map[string]int32{
	"MALE":   0,
	"FEMALE": 1,
}

func (x Sex) String() string {
	return proto.EnumName(Sex_name, int32(x))
}

func (Sex) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f0b0587afcdc51fc, []int{2}
}

type Status int32

const (
	Status_ACTIVE   Status = 0
	Status_INACTIVE Status = 1
)

var Status_name = map[int32]string{
	0: "ACTIVE",
	1: "INACTIVE",
}

var Status_value = map[string]int32{
	"ACTIVE":   0,
	"INACTIVE": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f0b0587afcdc51fc, []int{3}
}

// Basic Request
type BasicClientRequest struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *any.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicClientRequest) Reset()         { *m = BasicClientRequest{} }
func (m *BasicClientRequest) String() string { return proto.CompactTextString(m) }
func (*BasicClientRequest) ProtoMessage()    {}
func (*BasicClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b0587afcdc51fc, []int{0}
}

func (m *BasicClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicClientRequest.Unmarshal(m, b)
}
func (m *BasicClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicClientRequest.Marshal(b, m, deterministic)
}
func (m *BasicClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicClientRequest.Merge(m, src)
}
func (m *BasicClientRequest) XXX_Size() int {
	return xxx_messageInfo_BasicClientRequest.Size(m)
}
func (m *BasicClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BasicClientRequest proto.InternalMessageInfo

func (m *BasicClientRequest) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BasicClientRequest) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BasicClientRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Basic Response
type BasicServerResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 *any.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicServerResponse) Reset()         { *m = BasicServerResponse{} }
func (m *BasicServerResponse) String() string { return proto.CompactTextString(m) }
func (*BasicServerResponse) ProtoMessage()    {}
func (*BasicServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b0587afcdc51fc, []int{1}
}

func (m *BasicServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicServerResponse.Unmarshal(m, b)
}
func (m *BasicServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicServerResponse.Marshal(b, m, deterministic)
}
func (m *BasicServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicServerResponse.Merge(m, src)
}
func (m *BasicServerResponse) XXX_Size() int {
	return xxx_messageInfo_BasicServerResponse.Size(m)
}
func (m *BasicServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BasicServerResponse proto.InternalMessageInfo

func (m *BasicServerResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BasicServerResponse) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BasicServerResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UserProfile struct {
	Telephone            string               `protobuf:"bytes,1,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username             string               `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Nickname             string               `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string               `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Signature            string               `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	Sex                  Sex                  `protobuf:"varint,7,opt,name=sex,proto3,enum=com.salty.protos.Sex" json:"sex,omitempty"`
	Birthday             *timestamp.Timestamp `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Location             string               `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b0587afcdc51fc, []int{2}
}

func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfile.Unmarshal(m, b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
}
func (m *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(m, src)
}
func (m *UserProfile) XXX_Size() int {
	return xxx_messageInfo_UserProfile.Size(m)
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *UserProfile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserProfile) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserProfile) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserProfile) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserProfile) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *UserProfile) GetSex() Sex {
	if m != nil {
		return m.Sex
	}
	return Sex_MALE
}

func (m *UserProfile) GetBirthday() *timestamp.Timestamp {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *UserProfile) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type UserReq struct {
	CodeType             CodeType             `protobuf:"varint,1,opt,name=codeType,proto3,enum=com.salty.protos.CodeType" json:"codeType,omitempty"`
	VerificationCode     string               `protobuf:"bytes,2,opt,name=verificationCode,proto3" json:"verificationCode,omitempty"`
	UserProfile          *UserProfile         `protobuf:"bytes,3,opt,name=userProfile,proto3" json:"userProfile,omitempty"`
	Password             string               `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	DeviceID             string               `protobuf:"bytes,5,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Extension            *any.Any             `protobuf:"bytes,7,opt,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b0587afcdc51fc, []int{3}
}

func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (m *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(m, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

func (m *UserReq) GetCodeType() CodeType {
	if m != nil {
		return m.CodeType
	}
	return CodeType_REGISTER
}

func (m *UserReq) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

func (m *UserReq) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func (m *UserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserReq) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *UserReq) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *UserReq) GetExtension() *any.Any {
	if m != nil {
		return m.Extension
	}
	return nil
}

type UserResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResp) Reset()         { *m = UserResp{} }
func (m *UserResp) String() string { return proto.CompactTextString(m) }
func (*UserResp) ProtoMessage()    {}
func (*UserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b0587afcdc51fc, []int{4}
}

func (m *UserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResp.Unmarshal(m, b)
}
func (m *UserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResp.Marshal(b, m, deterministic)
}
func (m *UserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResp.Merge(m, src)
}
func (m *UserResp) XXX_Size() int {
	return xxx_messageInfo_UserResp.Size(m)
}
func (m *UserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserResp proto.InternalMessageInfo

type SMSReq struct {
	CodeType             CodeType `protobuf:"varint,1,opt,name=codeType,proto3,enum=com.salty.protos.CodeType" json:"codeType,omitempty"`
	Telephone            string   `protobuf:"bytes,2,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Extension            *any.Any `protobuf:"bytes,3,opt,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSReq) Reset()         { *m = SMSReq{} }
func (m *SMSReq) String() string { return proto.CompactTextString(m) }
func (*SMSReq) ProtoMessage()    {}
func (*SMSReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b0587afcdc51fc, []int{5}
}

func (m *SMSReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSReq.Unmarshal(m, b)
}
func (m *SMSReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSReq.Marshal(b, m, deterministic)
}
func (m *SMSReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSReq.Merge(m, src)
}
func (m *SMSReq) XXX_Size() int {
	return xxx_messageInfo_SMSReq.Size(m)
}
func (m *SMSReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSReq.DiscardUnknown(m)
}

var xxx_messageInfo_SMSReq proto.InternalMessageInfo

func (m *SMSReq) GetCodeType() CodeType {
	if m != nil {
		return m.CodeType
	}
	return CodeType_REGISTER
}

func (m *SMSReq) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *SMSReq) GetExtension() *any.Any {
	if m != nil {
		return m.Extension
	}
	return nil
}

type SMSResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SMSResp) Reset()         { *m = SMSResp{} }
func (m *SMSResp) String() string { return proto.CompactTextString(m) }
func (*SMSResp) ProtoMessage()    {}
func (*SMSResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0b0587afcdc51fc, []int{6}
}

func (m *SMSResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SMSResp.Unmarshal(m, b)
}
func (m *SMSResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SMSResp.Marshal(b, m, deterministic)
}
func (m *SMSResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SMSResp.Merge(m, src)
}
func (m *SMSResp) XXX_Size() int {
	return xxx_messageInfo_SMSResp.Size(m)
}
func (m *SMSResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SMSResp.DiscardUnknown(m)
}

var xxx_messageInfo_SMSResp proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("com.salty.protos.CodeType", CodeType_name, CodeType_value)
	proto.RegisterEnum("com.salty.protos.Role", Role_name, Role_value)
	proto.RegisterEnum("com.salty.protos.Sex", Sex_name, Sex_value)
	proto.RegisterEnum("com.salty.protos.Status", Status_name, Status_value)
	proto.RegisterType((*BasicClientRequest)(nil), "com.salty.protos.BasicClientRequest")
	proto.RegisterType((*BasicServerResponse)(nil), "com.salty.protos.BasicServerResponse")
	proto.RegisterType((*UserProfile)(nil), "com.salty.protos.UserProfile")
	proto.RegisterType((*UserReq)(nil), "com.salty.protos.UserReq")
	proto.RegisterType((*UserResp)(nil), "com.salty.protos.UserResp")
	proto.RegisterType((*SMSReq)(nil), "com.salty.protos.SMSReq")
	proto.RegisterType((*SMSResp)(nil), "com.salty.protos.SMSResp")
}

func init() { proto.RegisterFile("salty.proto", fileDescriptor_f0b0587afcdc51fc) }

var fileDescriptor_f0b0587afcdc51fc = []byte{
	// 680 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0xae, 0xf3, 0x6b, 0x4f, 0x7a, 0x7a, 0xa2, 0x3d, 0x3d, 0xc8, 0x04, 0x10, 0x51, 0x00, 0x11,
	0xe5, 0x22, 0x95, 0x82, 0x84, 0xb8, 0x43, 0x69, 0x9b, 0x56, 0x91, 0x92, 0xb6, 0x5a, 0xa7, 0x95,
	0xb8, 0x01, 0x6d, 0x9c, 0x69, 0xba, 0xc2, 0xf1, 0xba, 0xde, 0x4d, 0x48, 0x5e, 0x83, 0xe7, 0xe0,
	0x21, 0x78, 0x08, 0x1e, 0x08, 0xed, 0x3a, 0x4e, 0xda, 0x46, 0x54, 0x48, 0x94, 0x3b, 0x7f, 0x33,
	0x9f, 0x67, 0xbe, 0xfd, 0x66, 0x76, 0xa1, 0x24, 0x59, 0xa0, 0x16, 0xcd, 0x28, 0x16, 0x4a, 0x90,
	0xb2, 0x2f, 0x26, 0xcd, 0x1b, 0x01, 0x59, 0x79, 0x3e, 0x16, 0x62, 0x1c, 0xe0, 0x9e, 0x81, 0xc3,
	0xe9, 0xe5, 0x9e, 0xe2, 0x13, 0x94, 0x8a, 0x4d, 0xa2, 0x84, 0x51, 0x79, 0x7c, 0x97, 0xc0, 0xc2,
	0xe5, 0xcf, 0xb5, 0x00, 0xc8, 0x3e, 0x93, 0xdc, 0x3f, 0x08, 0x38, 0x86, 0x8a, 0xe2, 0xf5, 0x14,
	0xa5, 0x22, 0x04, 0x72, 0xbe, 0x18, 0xa1, 0x6b, 0x55, 0xad, 0x7a, 0x9e, 0x9a, 0x6f, 0x52, 0x87,
	0xdc, 0x88, 0x29, 0xe6, 0x66, 0xaa, 0x56, 0xbd, 0xd4, 0xda, 0x6d, 0x26, 0x35, 0x9b, 0x69, 0xcd,
	0x66, 0x3b, 0x5c, 0x50, 0xc3, 0x20, 0x2e, 0x14, 0x27, 0x28, 0x25, 0x1b, 0xa3, 0x9b, 0xad, 0x5a,
	0x75, 0x87, 0xa6, 0xb0, 0x36, 0x81, 0xff, 0x4c, 0x37, 0x0f, 0xe3, 0x19, 0xc6, 0x14, 0x65, 0x24,
	0x42, 0x89, 0x7f, 0xad, 0xdd, 0xb7, 0x0c, 0x94, 0xce, 0x25, 0xc6, 0x67, 0xb1, 0xb8, 0xe4, 0x01,
	0x92, 0xa7, 0xe0, 0x28, 0x0c, 0x30, 0xba, 0x12, 0x61, 0xd2, 0xcc, 0xa1, 0xeb, 0x00, 0xd9, 0x85,
	0x3c, 0x4e, 0x18, 0x0f, 0x4c, 0x4b, 0x87, 0x26, 0x80, 0x54, 0xc0, 0x9e, 0x4a, 0x8c, 0x43, 0x36,
	0x49, 0xcb, 0xaf, 0xb0, 0xce, 0x85, 0xdc, 0xff, 0x6c, 0x72, 0xb9, 0x24, 0x97, 0x62, 0xf2, 0x08,
	0x0a, 0x6c, 0xc6, 0x14, 0x8b, 0xdd, 0xbc, 0xc9, 0x2c, 0x91, 0xd6, 0x20, 0xf9, 0x38, 0x64, 0x6a,
	0x1a, 0xa3, 0x5b, 0x48, 0x34, 0xac, 0x02, 0xe4, 0x35, 0x64, 0x25, 0xce, 0xdd, 0x62, 0xd5, 0xaa,
	0xef, 0xb4, 0xfe, 0x6f, 0xde, 0x1d, 0x75, 0xd3, 0xc3, 0x39, 0xd5, 0x0c, 0xf2, 0x16, 0xec, 0x21,
	0x8f, 0xd5, 0xd5, 0x88, 0x2d, 0x5c, 0xdb, 0x58, 0x54, 0xd9, 0xb0, 0x68, 0x90, 0xae, 0x01, 0x5d,
	0x71, 0xb5, 0xe4, 0x40, 0xf8, 0x4c, 0x71, 0x11, 0xba, 0x4e, 0x22, 0x39, 0xc5, 0xb5, 0x1f, 0x19,
	0x28, 0x6a, 0xbb, 0x28, 0x5e, 0xeb, 0xfa, 0x7a, 0x0c, 0x83, 0x45, 0x94, 0x38, 0xb5, 0xd3, 0xaa,
	0x6c, 0xaa, 0x39, 0x58, 0x32, 0xe8, 0x8a, 0x4b, 0x1a, 0x50, 0x9e, 0x61, 0xcc, 0x2f, 0x79, 0x52,
	0x53, 0x33, 0x96, 0x7e, 0x6e, 0xc4, 0xc9, 0x7b, 0x28, 0x4d, 0xd7, 0xd3, 0x31, 0xee, 0x96, 0x5a,
	0xcf, 0x36, 0xdb, 0xdc, 0x18, 0x21, 0xbd, 0xf9, 0x87, 0x3e, 0x4c, 0xc4, 0xa4, 0xfc, 0x22, 0xe2,
	0x51, 0xea, 0x7f, 0x8a, 0x75, 0x6e, 0x84, 0x33, 0xee, 0x63, 0xf7, 0x70, 0x39, 0x81, 0x15, 0x26,
	0xef, 0xc0, 0xf1, 0x63, 0x64, 0x0a, 0x47, 0x6d, 0x65, 0x66, 0x70, 0xbf, 0x7b, 0x6b, 0x32, 0x69,
	0x81, 0x83, 0x73, 0x85, 0xa1, 0xd4, 0xfe, 0x15, 0xef, 0x59, 0xcd, 0x35, 0xad, 0x06, 0x60, 0x27,
	0xae, 0xca, 0xa8, 0xf6, 0xd5, 0x82, 0x82, 0xd7, 0xf7, 0xfe, 0xc4, 0xe1, 0x5b, 0x4b, 0x9c, 0xb9,
	0xbb, 0xc4, 0xb7, 0x04, 0x66, 0x7f, 0x4f, 0xa0, 0x03, 0x45, 0xa3, 0x49, 0x46, 0x8d, 0x17, 0x60,
	0xa7, 0x2d, 0xc9, 0x36, 0xd8, 0xb4, 0x73, 0xdc, 0xf5, 0x06, 0x1d, 0x5a, 0xde, 0x22, 0x0e, 0xe4,
	0x7b, 0xa7, 0xc7, 0xdd, 0x93, 0xb2, 0xd5, 0xd8, 0x83, 0x1c, 0x15, 0x01, 0x92, 0x12, 0x14, 0x0f,
	0x3b, 0x47, 0xed, 0xf3, 0xde, 0x20, 0xc9, 0xb7, 0x0f, 0xfb, 0xdd, 0x93, 0x32, 0x90, 0x7f, 0xa1,
	0xe4, 0x9d, 0x9f, 0x75, 0xe8, 0xa7, 0x24, 0xe0, 0x37, 0x9e, 0x40, 0xd6, 0xc3, 0x39, 0xb1, 0x21,
	0xd7, 0x6f, 0xf7, 0x3a, 0xe5, 0x2d, 0x02, 0x50, 0x38, 0xea, 0x98, 0x6f, 0xab, 0x51, 0x83, 0x82,
	0xa7, 0x98, 0x9a, 0x4a, 0x1d, 0x6d, 0x1f, 0x0c, 0xba, 0x17, 0x9a, 0xb1, 0x0d, 0x76, 0xf7, 0x64,
	0x89, 0xac, 0xd6, 0x77, 0x2b, 0xb9, 0xc8, 0xfa, 0xdd, 0xe0, 0x3e, 0x92, 0x0f, 0x60, 0x53, 0x1c,
	0x73, 0xa9, 0x30, 0x26, 0x2f, 0x37, 0x5d, 0xdb, 0x7c, 0xd1, 0x2a, 0xaf, 0x7e, 0xc1, 0xba, 0xfd,
	0x12, 0xd5, 0xb6, 0xc8, 0x05, 0xe4, 0x7b, 0x62, 0xcc, 0xc3, 0x07, 0xae, 0xdb, 0x0a, 0x00, 0xbc,
	0xbe, 0x97, 0x1e, 0xe0, 0x23, 0xfc, 0x73, 0x3a, 0x54, 0x8c, 0x87, 0x5e, 0xdf, 0x33, 0x77, 0xe1,
	0x61, 0xbb, 0xed, 0x67, 0xce, 0xac, 0x61, 0xc1, 0x30, 0xde, 0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff,
	0x13, 0x30, 0xbb, 0x38, 0x3e, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Register(ctx context.Context, in *BasicClientRequest, opts ...grpc.CallOption) (*BasicServerResponse, error)
	Login(ctx context.Context, in *BasicClientRequest, opts ...grpc.CallOption) (*BasicServerResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Register(ctx context.Context, in *BasicClientRequest, opts ...grpc.CallOption) (*BasicServerResponse, error) {
	out := new(BasicServerResponse)
	err := c.cc.Invoke(ctx, "/com.salty.protos.UserService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *BasicClientRequest, opts ...grpc.CallOption) (*BasicServerResponse, error) {
	out := new(BasicServerResponse)
	err := c.cc.Invoke(ctx, "/com.salty.protos.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Register(context.Context, *BasicClientRequest) (*BasicServerResponse, error)
	Login(context.Context, *BasicClientRequest) (*BasicServerResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Register(ctx context.Context, req *BasicClientRequest) (*BasicServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserServiceServer) Login(ctx context.Context, req *BasicClientRequest) (*BasicServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasicClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.UserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*BasicClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasicClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*BasicClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.salty.protos.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "salty.proto",
}

// SMSServiceClient is the client API for SMSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SMSServiceClient interface {
	ObtainSMSCode(ctx context.Context, in *BasicClientRequest, opts ...grpc.CallOption) (*BasicServerResponse, error)
}

type sMSServiceClient struct {
	cc *grpc.ClientConn
}

func NewSMSServiceClient(cc *grpc.ClientConn) SMSServiceClient {
	return &sMSServiceClient{cc}
}

func (c *sMSServiceClient) ObtainSMSCode(ctx context.Context, in *BasicClientRequest, opts ...grpc.CallOption) (*BasicServerResponse, error) {
	out := new(BasicServerResponse)
	err := c.cc.Invoke(ctx, "/com.salty.protos.SMSService/ObtainSMSCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SMSServiceServer is the server API for SMSService service.
type SMSServiceServer interface {
	ObtainSMSCode(context.Context, *BasicClientRequest) (*BasicServerResponse, error)
}

// UnimplementedSMSServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSMSServiceServer struct {
}

func (*UnimplementedSMSServiceServer) ObtainSMSCode(ctx context.Context, req *BasicClientRequest) (*BasicServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtainSMSCode not implemented")
}

func RegisterSMSServiceServer(s *grpc.Server, srv SMSServiceServer) {
	s.RegisterService(&_SMSService_serviceDesc, srv)
}

func _SMSService_ObtainSMSCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasicClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMSServiceServer).ObtainSMSCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.SMSService/ObtainSMSCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMSServiceServer).ObtainSMSCode(ctx, req.(*BasicClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SMSService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.salty.protos.SMSService",
	HandlerType: (*SMSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ObtainSMSCode",
			Handler:    _SMSService_ObtainSMSCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "salty.proto",
}
