// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contact.proto

package com_salty_protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestContactReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestContactReq) Reset()         { *m = RequestContactReq{} }
func (m *RequestContactReq) String() string { return proto.CompactTextString(m) }
func (*RequestContactReq) ProtoMessage()    {}
func (*RequestContactReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{0}
}

func (m *RequestContactReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestContactReq.Unmarshal(m, b)
}
func (m *RequestContactReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestContactReq.Marshal(b, m, deterministic)
}
func (m *RequestContactReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestContactReq.Merge(m, src)
}
func (m *RequestContactReq) XXX_Size() int {
	return xxx_messageInfo_RequestContactReq.Size(m)
}
func (m *RequestContactReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestContactReq.DiscardUnknown(m)
}

var xxx_messageInfo_RequestContactReq proto.InternalMessageInfo

func (m *RequestContactReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RequestContactReq) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type RequestContactResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestContactResp) Reset()         { *m = RequestContactResp{} }
func (m *RequestContactResp) String() string { return proto.CompactTextString(m) }
func (*RequestContactResp) ProtoMessage()    {}
func (*RequestContactResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{1}
}

func (m *RequestContactResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestContactResp.Unmarshal(m, b)
}
func (m *RequestContactResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestContactResp.Marshal(b, m, deterministic)
}
func (m *RequestContactResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestContactResp.Merge(m, src)
}
func (m *RequestContactResp) XXX_Size() int {
	return xxx_messageInfo_RequestContactResp.Size(m)
}
func (m *RequestContactResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestContactResp.DiscardUnknown(m)
}

var xxx_messageInfo_RequestContactResp proto.InternalMessageInfo

type RefusedContactReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefusedContactReq) Reset()         { *m = RefusedContactReq{} }
func (m *RefusedContactReq) String() string { return proto.CompactTextString(m) }
func (*RefusedContactReq) ProtoMessage()    {}
func (*RefusedContactReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{2}
}

func (m *RefusedContactReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefusedContactReq.Unmarshal(m, b)
}
func (m *RefusedContactReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefusedContactReq.Marshal(b, m, deterministic)
}
func (m *RefusedContactReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefusedContactReq.Merge(m, src)
}
func (m *RefusedContactReq) XXX_Size() int {
	return xxx_messageInfo_RefusedContactReq.Size(m)
}
func (m *RefusedContactReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefusedContactReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefusedContactReq proto.InternalMessageInfo

func (m *RefusedContactReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RefusedContactReq) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type RefusedContactResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefusedContactResp) Reset()         { *m = RefusedContactResp{} }
func (m *RefusedContactResp) String() string { return proto.CompactTextString(m) }
func (*RefusedContactResp) ProtoMessage()    {}
func (*RefusedContactResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{3}
}

func (m *RefusedContactResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefusedContactResp.Unmarshal(m, b)
}
func (m *RefusedContactResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefusedContactResp.Marshal(b, m, deterministic)
}
func (m *RefusedContactResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefusedContactResp.Merge(m, src)
}
func (m *RefusedContactResp) XXX_Size() int {
	return xxx_messageInfo_RefusedContactResp.Size(m)
}
func (m *RefusedContactResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RefusedContactResp.DiscardUnknown(m)
}

var xxx_messageInfo_RefusedContactResp proto.InternalMessageInfo

type AcceptContactReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptContactReq) Reset()         { *m = AcceptContactReq{} }
func (m *AcceptContactReq) String() string { return proto.CompactTextString(m) }
func (*AcceptContactReq) ProtoMessage()    {}
func (*AcceptContactReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{4}
}

func (m *AcceptContactReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptContactReq.Unmarshal(m, b)
}
func (m *AcceptContactReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptContactReq.Marshal(b, m, deterministic)
}
func (m *AcceptContactReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptContactReq.Merge(m, src)
}
func (m *AcceptContactReq) XXX_Size() int {
	return xxx_messageInfo_AcceptContactReq.Size(m)
}
func (m *AcceptContactReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptContactReq.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptContactReq proto.InternalMessageInfo

func (m *AcceptContactReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type AcceptContactResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcceptContactResp) Reset()         { *m = AcceptContactResp{} }
func (m *AcceptContactResp) String() string { return proto.CompactTextString(m) }
func (*AcceptContactResp) ProtoMessage()    {}
func (*AcceptContactResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{5}
}

func (m *AcceptContactResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcceptContactResp.Unmarshal(m, b)
}
func (m *AcceptContactResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcceptContactResp.Marshal(b, m, deterministic)
}
func (m *AcceptContactResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcceptContactResp.Merge(m, src)
}
func (m *AcceptContactResp) XXX_Size() int {
	return xxx_messageInfo_AcceptContactResp.Size(m)
}
func (m *AcceptContactResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AcceptContactResp.DiscardUnknown(m)
}

var xxx_messageInfo_AcceptContactResp proto.InternalMessageInfo

type DeleteContactReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteContactReq) Reset()         { *m = DeleteContactReq{} }
func (m *DeleteContactReq) String() string { return proto.CompactTextString(m) }
func (*DeleteContactReq) ProtoMessage()    {}
func (*DeleteContactReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{6}
}

func (m *DeleteContactReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContactReq.Unmarshal(m, b)
}
func (m *DeleteContactReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContactReq.Marshal(b, m, deterministic)
}
func (m *DeleteContactReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContactReq.Merge(m, src)
}
func (m *DeleteContactReq) XXX_Size() int {
	return xxx_messageInfo_DeleteContactReq.Size(m)
}
func (m *DeleteContactReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContactReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContactReq proto.InternalMessageInfo

func (m *DeleteContactReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteContactResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteContactResp) Reset()         { *m = DeleteContactResp{} }
func (m *DeleteContactResp) String() string { return proto.CompactTextString(m) }
func (*DeleteContactResp) ProtoMessage()    {}
func (*DeleteContactResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{7}
}

func (m *DeleteContactResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContactResp.Unmarshal(m, b)
}
func (m *DeleteContactResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContactResp.Marshal(b, m, deterministic)
}
func (m *DeleteContactResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContactResp.Merge(m, src)
}
func (m *DeleteContactResp) XXX_Size() int {
	return xxx_messageInfo_DeleteContactResp.Size(m)
}
func (m *DeleteContactResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContactResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContactResp proto.InternalMessageInfo

type UpdateRemarkInfoReq struct {
	UserId               string         `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	RemarkInfo           *ContactRemark `protobuf:"bytes,2,opt,name=remarkInfo,proto3" json:"remarkInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpdateRemarkInfoReq) Reset()         { *m = UpdateRemarkInfoReq{} }
func (m *UpdateRemarkInfoReq) String() string { return proto.CompactTextString(m) }
func (*UpdateRemarkInfoReq) ProtoMessage()    {}
func (*UpdateRemarkInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{8}
}

func (m *UpdateRemarkInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRemarkInfoReq.Unmarshal(m, b)
}
func (m *UpdateRemarkInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRemarkInfoReq.Marshal(b, m, deterministic)
}
func (m *UpdateRemarkInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRemarkInfoReq.Merge(m, src)
}
func (m *UpdateRemarkInfoReq) XXX_Size() int {
	return xxx_messageInfo_UpdateRemarkInfoReq.Size(m)
}
func (m *UpdateRemarkInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRemarkInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRemarkInfoReq proto.InternalMessageInfo

func (m *UpdateRemarkInfoReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateRemarkInfoReq) GetRemarkInfo() *ContactRemark {
	if m != nil {
		return m.RemarkInfo
	}
	return nil
}

type UpdateRemarkInfoResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRemarkInfoResp) Reset()         { *m = UpdateRemarkInfoResp{} }
func (m *UpdateRemarkInfoResp) String() string { return proto.CompactTextString(m) }
func (*UpdateRemarkInfoResp) ProtoMessage()    {}
func (*UpdateRemarkInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5036fff2565fb15, []int{9}
}

func (m *UpdateRemarkInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRemarkInfoResp.Unmarshal(m, b)
}
func (m *UpdateRemarkInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRemarkInfoResp.Marshal(b, m, deterministic)
}
func (m *UpdateRemarkInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRemarkInfoResp.Merge(m, src)
}
func (m *UpdateRemarkInfoResp) XXX_Size() int {
	return xxx_messageInfo_UpdateRemarkInfoResp.Size(m)
}
func (m *UpdateRemarkInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRemarkInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRemarkInfoResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RequestContactReq)(nil), "com.salty.protos.RequestContactReq")
	proto.RegisterType((*RequestContactResp)(nil), "com.salty.protos.RequestContactResp")
	proto.RegisterType((*RefusedContactReq)(nil), "com.salty.protos.RefusedContactReq")
	proto.RegisterType((*RefusedContactResp)(nil), "com.salty.protos.RefusedContactResp")
	proto.RegisterType((*AcceptContactReq)(nil), "com.salty.protos.AcceptContactReq")
	proto.RegisterType((*AcceptContactResp)(nil), "com.salty.protos.AcceptContactResp")
	proto.RegisterType((*DeleteContactReq)(nil), "com.salty.protos.DeleteContactReq")
	proto.RegisterType((*DeleteContactResp)(nil), "com.salty.protos.DeleteContactResp")
	proto.RegisterType((*UpdateRemarkInfoReq)(nil), "com.salty.protos.UpdateRemarkInfoReq")
	proto.RegisterType((*UpdateRemarkInfoResp)(nil), "com.salty.protos.UpdateRemarkInfoResp")
}

func init() { proto.RegisterFile("contact.proto", fileDescriptor_a5036fff2565fb15) }

var fileDescriptor_a5036fff2565fb15 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xdd, 0x0a, 0x05, 0x47, 0x5b, 0xb6, 0xdb, 0x52, 0xea, 0x5e, 0x94, 0x9c, 0xc4, 0xc3,
	0x1e, 0xea, 0x03, 0x88, 0x56, 0xd0, 0xc5, 0x8b, 0x44, 0x7c, 0x80, 0x98, 0x9d, 0x42, 0xb1, 0x4d,
	0xb2, 0x99, 0xac, 0xe0, 0x13, 0xf8, 0xda, 0xd2, 0xa6, 0x96, 0x6e, 0x8a, 0x52, 0xb6, 0xc7, 0xf9,
	0xf3, 0xcf, 0x37, 0x99, 0xf9, 0xa1, 0x23, 0xb5, 0x72, 0x42, 0xba, 0xcc, 0x58, 0xed, 0x74, 0x12,
	0x4b, 0xbd, 0xc8, 0x48, 0xcc, 0xdd, 0x97, 0x17, 0x28, 0x3d, 0x43, 0xe5, 0x66, 0xbf, 0x25, 0x9b,
	0x40, 0x8f, 0x63, 0x59, 0x21, 0xb9, 0x89, 0xef, 0xe3, 0x58, 0x26, 0x43, 0x68, 0x57, 0x84, 0x36,
	0x2f, 0x46, 0xd1, 0x65, 0x74, 0x75, 0xc2, 0xd7, 0xd5, 0x52, 0xb7, 0x28, 0x48, 0xab, 0x51, 0xcb,
	0xeb, 0xbe, 0x62, 0x03, 0x48, 0x42, 0x08, 0x19, 0x8f, 0x9e, 0x56, 0x84, 0xc5, 0xa1, 0xe8, 0x3a,
	0x84, 0x0c, 0xbb, 0x86, 0xf8, 0x4e, 0x4a, 0x34, 0x7b, 0x7c, 0x9a, 0xf5, 0xa1, 0x17, 0x78, 0x3d,
	0xe0, 0x01, 0xe7, 0xe8, 0x70, 0x3f, 0x40, 0xe0, 0x25, 0xc3, 0x14, 0xf4, 0xdf, 0x4c, 0x21, 0x1c,
	0x72, 0x5c, 0x08, 0xfb, 0x91, 0xab, 0xa9, 0xfe, 0x6f, 0xbd, 0x5b, 0x00, 0xbb, 0x31, 0xae, 0x56,
	0x3c, 0x1d, 0x5f, 0x64, 0x61, 0x36, 0xd9, 0x66, 0xc2, 0xd2, 0xca, 0xb7, 0x5a, 0xd8, 0x10, 0x06,
	0xbb, 0xf3, 0xc8, 0x8c, 0xbf, 0x8f, 0xa1, 0xbb, 0xee, 0x7a, 0x45, 0xfb, 0x39, 0x93, 0x98, 0xe4,
	0xd0, 0xad, 0xa7, 0x91, 0x9c, 0xef, 0x4e, 0x7a, 0xb4, 0x46, 0x72, 0x2c, 0xd3, 0xf4, 0xaf, 0x27,
	0x32, 0xec, 0xc8, 0xa3, 0xb6, 0xaf, 0xdf, 0x1c, 0xf5, 0x04, 0x9d, 0x5a, 0x0c, 0x07, 0x91, 0x6a,
	0x79, 0x34, 0x27, 0x3d, 0x43, 0x1c, 0x1e, 0xb5, 0x31, 0xec, 0xbe, 0xf5, 0x12, 0xbd, 0xb7, 0x57,
	0xf2, 0xcd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x82, 0x77, 0x19, 0x85, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactServiceClient is the client API for ContactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactServiceClient interface {
	//请求添加好友
	RequestContact(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//拒绝添加好友，同时可以输入拒绝的原因
	RefusedContact(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//同意添加
	AcceptContact(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//删除好友
	DeleteContact(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//更新好友备注信息
	UpdateRemarkInfo(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
}

type contactServiceClient struct {
	cc *grpc.ClientConn
}

func NewContactServiceClient(cc *grpc.ClientConn) ContactServiceClient {
	return &contactServiceClient{cc}
}

func (c *contactServiceClient) RequestContact(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.ContactService/RequestContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) RefusedContact(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.ContactService/RefusedContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) AcceptContact(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.ContactService/AcceptContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) DeleteContact(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.ContactService/DeleteContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactServiceClient) UpdateRemarkInfo(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.ContactService/UpdateRemarkInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactServiceServer is the server API for ContactService service.
type ContactServiceServer interface {
	//请求添加好友
	RequestContact(context.Context, *GrpcReq) (*GrpcResp, error)
	//拒绝添加好友，同时可以输入拒绝的原因
	RefusedContact(context.Context, *GrpcReq) (*GrpcResp, error)
	//同意添加
	AcceptContact(context.Context, *GrpcReq) (*GrpcResp, error)
	//删除好友
	DeleteContact(context.Context, *GrpcReq) (*GrpcResp, error)
	//更新好友备注信息
	UpdateRemarkInfo(context.Context, *GrpcReq) (*GrpcResp, error)
}

// UnimplementedContactServiceServer can be embedded to have forward compatible implementations.
type UnimplementedContactServiceServer struct {
}

func (*UnimplementedContactServiceServer) RequestContact(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestContact not implemented")
}
func (*UnimplementedContactServiceServer) RefusedContact(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefusedContact not implemented")
}
func (*UnimplementedContactServiceServer) AcceptContact(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptContact not implemented")
}
func (*UnimplementedContactServiceServer) DeleteContact(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContact not implemented")
}
func (*UnimplementedContactServiceServer) UpdateRemarkInfo(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRemarkInfo not implemented")
}

func RegisterContactServiceServer(s *grpc.Server, srv ContactServiceServer) {
	s.RegisterService(&_ContactService_serviceDesc, srv)
}

func _ContactService_RequestContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).RequestContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.ContactService/RequestContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).RequestContact(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_RefusedContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).RefusedContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.ContactService/RefusedContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).RefusedContact(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_AcceptContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).AcceptContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.ContactService/AcceptContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).AcceptContact(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_DeleteContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).DeleteContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.ContactService/DeleteContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).DeleteContact(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactService_UpdateRemarkInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactServiceServer).UpdateRemarkInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.ContactService/UpdateRemarkInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactServiceServer).UpdateRemarkInfo(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.salty.protos.ContactService",
	HandlerType: (*ContactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestContact",
			Handler:    _ContactService_RequestContact_Handler,
		},
		{
			MethodName: "RefusedContact",
			Handler:    _ContactService_RefusedContact_Handler,
		},
		{
			MethodName: "AcceptContact",
			Handler:    _ContactService_AcceptContact_Handler,
		},
		{
			MethodName: "DeleteContact",
			Handler:    _ContactService_DeleteContact_Handler,
		},
		{
			MethodName: "UpdateRemarkInfo",
			Handler:    _ContactService_UpdateRemarkInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contact.proto",
}
