// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity.proto

package com_salty_protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GrpcReq_Language int32

const (
	GrpcReq_CHINESE GrpcReq_Language = 0
	GrpcReq_ENGLISH GrpcReq_Language = 1
)

var GrpcReq_Language_name = map[int32]string{
	0: "CHINESE",
	1: "ENGLISH",
}

var GrpcReq_Language_value = map[string]int32{
	"CHINESE": 0,
	"ENGLISH": 1,
}

func (x GrpcReq_Language) String() string {
	return proto.EnumName(GrpcReq_Language_name, int32(x))
}

func (GrpcReq_Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0, 0}
}

type GrpcReq_OS int32

const (
	GrpcReq_UNKNOWN GrpcReq_OS = 0
	GrpcReq_ANDROID GrpcReq_OS = 1
	GrpcReq_IOS     GrpcReq_OS = 2
	GrpcReq_WINDOWS GrpcReq_OS = 3
)

var GrpcReq_OS_name = map[int32]string{
	0: "UNKNOWN",
	1: "ANDROID",
	2: "IOS",
	3: "WINDOWS",
}

var GrpcReq_OS_value = map[string]int32{
	"UNKNOWN": 0,
	"ANDROID": 1,
	"IOS":     2,
	"WINDOWS": 3,
}

func (x GrpcReq_OS) String() string {
	return proto.EnumName(GrpcReq_OS_name, int32(x))
}

func (GrpcReq_OS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0, 1}
}

type UserProfile_Sex int32

const (
	UserProfile_NOT_SET UserProfile_Sex = 0
	UserProfile_MALE    UserProfile_Sex = 1
	UserProfile_FEMALE  UserProfile_Sex = 2
)

var UserProfile_Sex_name = map[int32]string{
	0: "NOT_SET",
	1: "MALE",
	2: "FEMALE",
}

var UserProfile_Sex_value = map[string]int32{
	"NOT_SET": 0,
	"MALE":    1,
	"FEMALE":  2,
}

func (x UserProfile_Sex) String() string {
	return proto.EnumName(UserProfile_Sex_name, int32(x))
}

func (UserProfile_Sex) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{2, 0}
}

type GroupMemberProfile_GroupRole int32

const (
	GroupMemberProfile_NONE          GroupMemberProfile_GroupRole = 0
	GroupMemberProfile_ADMINISTRATOR GroupMemberProfile_GroupRole = 1
)

var GroupMemberProfile_GroupRole_name = map[int32]string{
	0: "NONE",
	1: "ADMINISTRATOR",
}

var GroupMemberProfile_GroupRole_value = map[string]int32{
	"NONE":          0,
	"ADMINISTRATOR": 1,
}

func (x GroupMemberProfile_GroupRole) String() string {
	return proto.EnumName(GroupMemberProfile_GroupRole_name, int32(x))
}

func (GroupMemberProfile_GroupRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{6, 0}
}

//会话类型
type Conversation_ConversationType int32

const (
	Conversation_NONE    Conversation_ConversationType = 0
	Conversation_PRIVATE Conversation_ConversationType = 1
	Conversation_GROUP   Conversation_ConversationType = 2
)

var Conversation_ConversationType_name = map[int32]string{
	0: "NONE",
	1: "PRIVATE",
	2: "GROUP",
}

var Conversation_ConversationType_value = map[string]int32{
	"NONE":    0,
	"PRIVATE": 1,
	"GROUP":   2,
}

func (x Conversation_ConversationType) String() string {
	return proto.EnumName(Conversation_ConversationType_name, int32(x))
}

func (Conversation_ConversationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{7, 0}
}

//会话提醒状态
type Conversation_NotificationStatus int32

const (
	Conversation_NOTIFY         Conversation_NotificationStatus = 0
	Conversation_DO_NOT_DISTURB Conversation_NotificationStatus = 1
)

var Conversation_NotificationStatus_name = map[int32]string{
	0: "NOTIFY",
	1: "DO_NOT_DISTURB",
}

var Conversation_NotificationStatus_value = map[string]int32{
	"NOTIFY":         0,
	"DO_NOT_DISTURB": 1,
}

func (x Conversation_NotificationStatus) String() string {
	return proto.EnumName(Conversation_NotificationStatus_name, int32(x))
}

func (Conversation_NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{7, 1}
}

//会话提醒状态
type Message_SentStatus int32

const (
	Message_SENDING Message_SentStatus = 0
	Message_FAILED  Message_SentStatus = 1
	Message_READ    Message_SentStatus = 2
)

var Message_SentStatus_name = map[int32]string{
	0: "SENDING",
	1: "FAILED",
	2: "READ",
}

var Message_SentStatus_value = map[string]int32{
	"SENDING": 0,
	"FAILED":  1,
	"READ":    2,
}

func (x Message_SentStatus) String() string {
	return proto.EnumName(Message_SentStatus_name, int32(x))
}

func (Message_SentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{8, 0}
}

//会话提醒状态
type Message_ReceivedStatus int32

const (
	Message_RECEIVED   Message_ReceivedStatus = 0
	Message_DOWNLOADED Message_ReceivedStatus = 1
)

var Message_ReceivedStatus_name = map[int32]string{
	0: "RECEIVED",
	1: "DOWNLOADED",
}

var Message_ReceivedStatus_value = map[string]int32{
	"RECEIVED":   0,
	"DOWNLOADED": 1,
}

func (x Message_ReceivedStatus) String() string {
	return proto.EnumName(Message_ReceivedStatus_name, int32(x))
}

func (Message_ReceivedStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{8, 1}
}

//消息的发送方向
type Message_MessageDirection int32

const (
	Message_SEND    Message_MessageDirection = 0
	Message_RECEIVE Message_MessageDirection = 1
)

var Message_MessageDirection_name = map[int32]string{
	0: "SEND",
	1: "RECEIVE",
}

var Message_MessageDirection_value = map[string]int32{
	"SEND":    0,
	"RECEIVE": 1,
}

func (x Message_MessageDirection) String() string {
	return proto.EnumName(Message_MessageDirection_name, int32(x))
}

func (Message_MessageDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{8, 2}
}

// Basic Request
type GrpcReq struct {
	DeviceId             string           `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Version              string           `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Language             GrpcReq_Language `protobuf:"varint,3,opt,name=language,proto3,enum=com.salty.protos.GrpcReq_Language" json:"language,omitempty"`
	Os                   GrpcReq_OS       `protobuf:"varint,4,opt,name=os,proto3,enum=com.salty.protos.GrpcReq_OS" json:"os,omitempty"`
	Token                string           `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Data                 *any.Any         `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GrpcReq) Reset()         { *m = GrpcReq{} }
func (m *GrpcReq) String() string { return proto.CompactTextString(m) }
func (*GrpcReq) ProtoMessage()    {}
func (*GrpcReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0}
}

func (m *GrpcReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcReq.Unmarshal(m, b)
}
func (m *GrpcReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcReq.Marshal(b, m, deterministic)
}
func (m *GrpcReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcReq.Merge(m, src)
}
func (m *GrpcReq) XXX_Size() int {
	return xxx_messageInfo_GrpcReq.Size(m)
}
func (m *GrpcReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcReq.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcReq proto.InternalMessageInfo

func (m *GrpcReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *GrpcReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GrpcReq) GetLanguage() GrpcReq_Language {
	if m != nil {
		return m.Language
	}
	return GrpcReq_CHINESE
}

func (m *GrpcReq) GetOs() GrpcReq_OS {
	if m != nil {
		return m.Os
	}
	return GrpcReq_UNKNOWN
}

func (m *GrpcReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GrpcReq) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

// Basic Response
type GrpcResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *any.Any `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcResp) Reset()         { *m = GrpcResp{} }
func (m *GrpcResp) String() string { return proto.CompactTextString(m) }
func (*GrpcResp) ProtoMessage()    {}
func (*GrpcResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{1}
}

func (m *GrpcResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcResp.Unmarshal(m, b)
}
func (m *GrpcResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcResp.Marshal(b, m, deterministic)
}
func (m *GrpcResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcResp.Merge(m, src)
}
func (m *GrpcResp) XXX_Size() int {
	return xxx_messageInfo_GrpcResp.Size(m)
}
func (m *GrpcResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcResp.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcResp proto.InternalMessageInfo

func (m *GrpcResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GrpcResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GrpcResp) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserProfile struct {
	UserId               string          `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Telephone            string          `protobuf:"bytes,2,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Email                string          `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname             string          `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string          `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description          string          `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Sex                  UserProfile_Sex `protobuf:"varint,7,opt,name=sex,proto3,enum=com.salty.protos.UserProfile_Sex" json:"sex,omitempty"`
	Birthday             int64           `protobuf:"varint,8,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Location             string          `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{2}
}

func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfile.Unmarshal(m, b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
}
func (m *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(m, src)
}
func (m *UserProfile) XXX_Size() int {
	return xxx_messageInfo_UserProfile.Size(m)
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserProfile) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *UserProfile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserProfile) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserProfile) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserProfile) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UserProfile) GetSex() UserProfile_Sex {
	if m != nil {
		return m.Sex
	}
	return UserProfile_NOT_SET
}

func (m *UserProfile) GetBirthday() int64 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *UserProfile) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type ContactProfile struct {
	UserProfile          *UserProfile   `protobuf:"bytes,1,opt,name=userProfile,proto3" json:"userProfile,omitempty"`
	RemarkInfo           *ContactRemark `protobuf:"bytes,2,opt,name=remarkInfo,proto3" json:"remarkInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ContactProfile) Reset()         { *m = ContactProfile{} }
func (m *ContactProfile) String() string { return proto.CompactTextString(m) }
func (*ContactProfile) ProtoMessage()    {}
func (*ContactProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{3}
}

func (m *ContactProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactProfile.Unmarshal(m, b)
}
func (m *ContactProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactProfile.Marshal(b, m, deterministic)
}
func (m *ContactProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactProfile.Merge(m, src)
}
func (m *ContactProfile) XXX_Size() int {
	return xxx_messageInfo_ContactProfile.Size(m)
}
func (m *ContactProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ContactProfile proto.InternalMessageInfo

func (m *ContactProfile) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

func (m *ContactProfile) GetRemarkInfo() *ContactRemark {
	if m != nil {
		return m.RemarkInfo
	}
	return nil
}

type ContactRemark struct {
	RemarkName           string   `protobuf:"bytes,1,opt,name=remarkName,proto3" json:"remarkName,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Telephones           []string `protobuf:"bytes,3,rep,name=telephones,proto3" json:"telephones,omitempty"`
	Tags                 []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactRemark) Reset()         { *m = ContactRemark{} }
func (m *ContactRemark) String() string { return proto.CompactTextString(m) }
func (*ContactRemark) ProtoMessage()    {}
func (*ContactRemark) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{4}
}

func (m *ContactRemark) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactRemark.Unmarshal(m, b)
}
func (m *ContactRemark) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactRemark.Marshal(b, m, deterministic)
}
func (m *ContactRemark) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactRemark.Merge(m, src)
}
func (m *ContactRemark) XXX_Size() int {
	return xxx_messageInfo_ContactRemark.Size(m)
}
func (m *ContactRemark) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactRemark.DiscardUnknown(m)
}

var xxx_messageInfo_ContactRemark proto.InternalMessageInfo

func (m *ContactRemark) GetRemarkName() string {
	if m != nil {
		return m.RemarkName
	}
	return ""
}

func (m *ContactRemark) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ContactRemark) GetTelephones() []string {
	if m != nil {
		return m.Telephones
	}
	return nil
}

func (m *ContactRemark) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type GroupProfile struct {
	GroupId              string                `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime           int64                 `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	OwnerUserId          string                `protobuf:"bytes,4,opt,name=ownerUserId,proto3" json:"ownerUserId,omitempty"`
	Avatar               string                `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Notice               string                `protobuf:"bytes,6,opt,name=notice,proto3" json:"notice,omitempty"`
	Members              []*GroupMemberProfile `protobuf:"bytes,7,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GroupProfile) Reset()         { *m = GroupProfile{} }
func (m *GroupProfile) String() string { return proto.CompactTextString(m) }
func (*GroupProfile) ProtoMessage()    {}
func (*GroupProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{5}
}

func (m *GroupProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupProfile.Unmarshal(m, b)
}
func (m *GroupProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupProfile.Marshal(b, m, deterministic)
}
func (m *GroupProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupProfile.Merge(m, src)
}
func (m *GroupProfile) XXX_Size() int {
	return xxx_messageInfo_GroupProfile.Size(m)
}
func (m *GroupProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupProfile.DiscardUnknown(m)
}

var xxx_messageInfo_GroupProfile proto.InternalMessageInfo

func (m *GroupProfile) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GroupProfile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GroupProfile) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *GroupProfile) GetOwnerUserId() string {
	if m != nil {
		return m.OwnerUserId
	}
	return ""
}

func (m *GroupProfile) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *GroupProfile) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

func (m *GroupProfile) GetMembers() []*GroupMemberProfile {
	if m != nil {
		return m.Members
	}
	return nil
}

type GroupMemberProfile struct {
	GroupId              string                       `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Alias                string                       `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias,omitempty"`
	Role                 GroupMemberProfile_GroupRole `protobuf:"varint,3,opt,name=role,proto3,enum=com.salty.protos.GroupMemberProfile_GroupRole" json:"role,omitempty"`
	JoinTime             int64                        `protobuf:"varint,4,opt,name=joinTime,proto3" json:"joinTime,omitempty"`
	UserProfile          *UserProfile                 `protobuf:"bytes,5,opt,name=userProfile,proto3" json:"userProfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GroupMemberProfile) Reset()         { *m = GroupMemberProfile{} }
func (m *GroupMemberProfile) String() string { return proto.CompactTextString(m) }
func (*GroupMemberProfile) ProtoMessage()    {}
func (*GroupMemberProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{6}
}

func (m *GroupMemberProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMemberProfile.Unmarshal(m, b)
}
func (m *GroupMemberProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMemberProfile.Marshal(b, m, deterministic)
}
func (m *GroupMemberProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMemberProfile.Merge(m, src)
}
func (m *GroupMemberProfile) XXX_Size() int {
	return xxx_messageInfo_GroupMemberProfile.Size(m)
}
func (m *GroupMemberProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMemberProfile.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMemberProfile proto.InternalMessageInfo

func (m *GroupMemberProfile) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *GroupMemberProfile) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

func (m *GroupMemberProfile) GetRole() GroupMemberProfile_GroupRole {
	if m != nil {
		return m.Role
	}
	return GroupMemberProfile_NONE
}

func (m *GroupMemberProfile) GetJoinTime() int64 {
	if m != nil {
		return m.JoinTime
	}
	return 0
}

func (m *GroupMemberProfile) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type Conversation struct {
	ConversationId       string                          `protobuf:"bytes,1,opt,name=conversationId,proto3" json:"conversationId,omitempty"`
	ConversationTitle    string                          `protobuf:"bytes,2,opt,name=conversationTitle,proto3" json:"conversationTitle,omitempty"`
	PortraitUrl          string                          `protobuf:"bytes,3,opt,name=portraitUrl,proto3" json:"portraitUrl,omitempty"`
	UnreadMessageCount   int32                           `protobuf:"varint,4,opt,name=unreadMessageCount,proto3" json:"unreadMessageCount,omitempty"`
	IsTop                bool                            `protobuf:"varint,5,opt,name=isTop,proto3" json:"isTop,omitempty"`
	LatestMessage        *Message                        `protobuf:"bytes,6,opt,name=latestMessage,proto3" json:"latestMessage,omitempty"`
	Draft                string                          `protobuf:"bytes,7,opt,name=draft,proto3" json:"draft,omitempty"`
	ConversationType     Conversation_ConversationType   `protobuf:"varint,8,opt,name=conversationType,proto3,enum=com.salty.protos.Conversation_ConversationType" json:"conversationType,omitempty"`
	NotificationStatus   Conversation_NotificationStatus `protobuf:"varint,9,opt,name=notificationStatus,proto3,enum=com.salty.protos.Conversation_NotificationStatus" json:"notificationStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *Conversation) Reset()         { *m = Conversation{} }
func (m *Conversation) String() string { return proto.CompactTextString(m) }
func (*Conversation) ProtoMessage()    {}
func (*Conversation) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{7}
}

func (m *Conversation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversation.Unmarshal(m, b)
}
func (m *Conversation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversation.Marshal(b, m, deterministic)
}
func (m *Conversation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversation.Merge(m, src)
}
func (m *Conversation) XXX_Size() int {
	return xxx_messageInfo_Conversation.Size(m)
}
func (m *Conversation) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversation.DiscardUnknown(m)
}

var xxx_messageInfo_Conversation proto.InternalMessageInfo

func (m *Conversation) GetConversationId() string {
	if m != nil {
		return m.ConversationId
	}
	return ""
}

func (m *Conversation) GetConversationTitle() string {
	if m != nil {
		return m.ConversationTitle
	}
	return ""
}

func (m *Conversation) GetPortraitUrl() string {
	if m != nil {
		return m.PortraitUrl
	}
	return ""
}

func (m *Conversation) GetUnreadMessageCount() int32 {
	if m != nil {
		return m.UnreadMessageCount
	}
	return 0
}

func (m *Conversation) GetIsTop() bool {
	if m != nil {
		return m.IsTop
	}
	return false
}

func (m *Conversation) GetLatestMessage() *Message {
	if m != nil {
		return m.LatestMessage
	}
	return nil
}

func (m *Conversation) GetDraft() string {
	if m != nil {
		return m.Draft
	}
	return ""
}

func (m *Conversation) GetConversationType() Conversation_ConversationType {
	if m != nil {
		return m.ConversationType
	}
	return Conversation_NONE
}

func (m *Conversation) GetNotificationStatus() Conversation_NotificationStatus {
	if m != nil {
		return m.NotificationStatus
	}
	return Conversation_NOTIFY
}

type Message struct {
	MessageID            string                 `protobuf:"bytes,1,opt,name=messageID,proto3" json:"messageID,omitempty"`
	SortID               string                 `protobuf:"bytes,2,opt,name=sortID,proto3" json:"sortID,omitempty"`
	SenderUserId         string                 `protobuf:"bytes,3,opt,name=senderUserId,proto3" json:"senderUserId,omitempty"`
	TargetId             string                 `protobuf:"bytes,4,opt,name=targetId,proto3" json:"targetId,omitempty"`
	SendTime             int64                  `protobuf:"varint,5,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	ReceivedTime         int64                  `protobuf:"varint,6,opt,name=receivedTime,proto3" json:"receivedTime,omitempty"`
	ReadTime             int64                  `protobuf:"varint,7,opt,name=readTime,proto3" json:"readTime,omitempty"`
	SentStatus           Message_SentStatus     `protobuf:"varint,8,opt,name=sentStatus,proto3,enum=com.salty.protos.Message_SentStatus" json:"sentStatus,omitempty"`
	ReceivedStatus       Message_ReceivedStatus `protobuf:"varint,9,opt,name=receivedStatus,proto3,enum=com.salty.protos.Message_ReceivedStatus" json:"receivedStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{8}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func (m *Message) GetSortID() string {
	if m != nil {
		return m.SortID
	}
	return ""
}

func (m *Message) GetSenderUserId() string {
	if m != nil {
		return m.SenderUserId
	}
	return ""
}

func (m *Message) GetTargetId() string {
	if m != nil {
		return m.TargetId
	}
	return ""
}

func (m *Message) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *Message) GetReceivedTime() int64 {
	if m != nil {
		return m.ReceivedTime
	}
	return 0
}

func (m *Message) GetReadTime() int64 {
	if m != nil {
		return m.ReadTime
	}
	return 0
}

func (m *Message) GetSentStatus() Message_SentStatus {
	if m != nil {
		return m.SentStatus
	}
	return Message_SENDING
}

func (m *Message) GetReceivedStatus() Message_ReceivedStatus {
	if m != nil {
		return m.ReceivedStatus
	}
	return Message_RECEIVED
}

type EmptyResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResp) Reset()         { *m = EmptyResp{} }
func (m *EmptyResp) String() string { return proto.CompactTextString(m) }
func (*EmptyResp) ProtoMessage()    {}
func (*EmptyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{9}
}

func (m *EmptyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResp.Unmarshal(m, b)
}
func (m *EmptyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResp.Marshal(b, m, deterministic)
}
func (m *EmptyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResp.Merge(m, src)
}
func (m *EmptyResp) XXX_Size() int {
	return xxx_messageInfo_EmptyResp.Size(m)
}
func (m *EmptyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResp.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResp proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("com.salty.protos.GrpcReq_Language", GrpcReq_Language_name, GrpcReq_Language_value)
	proto.RegisterEnum("com.salty.protos.GrpcReq_OS", GrpcReq_OS_name, GrpcReq_OS_value)
	proto.RegisterEnum("com.salty.protos.UserProfile_Sex", UserProfile_Sex_name, UserProfile_Sex_value)
	proto.RegisterEnum("com.salty.protos.GroupMemberProfile_GroupRole", GroupMemberProfile_GroupRole_name, GroupMemberProfile_GroupRole_value)
	proto.RegisterEnum("com.salty.protos.Conversation_ConversationType", Conversation_ConversationType_name, Conversation_ConversationType_value)
	proto.RegisterEnum("com.salty.protos.Conversation_NotificationStatus", Conversation_NotificationStatus_name, Conversation_NotificationStatus_value)
	proto.RegisterEnum("com.salty.protos.Message_SentStatus", Message_SentStatus_name, Message_SentStatus_value)
	proto.RegisterEnum("com.salty.protos.Message_ReceivedStatus", Message_ReceivedStatus_name, Message_ReceivedStatus_value)
	proto.RegisterEnum("com.salty.protos.Message_MessageDirection", Message_MessageDirection_name, Message_MessageDirection_value)
	proto.RegisterType((*GrpcReq)(nil), "com.salty.protos.GrpcReq")
	proto.RegisterType((*GrpcResp)(nil), "com.salty.protos.GrpcResp")
	proto.RegisterType((*UserProfile)(nil), "com.salty.protos.UserProfile")
	proto.RegisterType((*ContactProfile)(nil), "com.salty.protos.ContactProfile")
	proto.RegisterType((*ContactRemark)(nil), "com.salty.protos.ContactRemark")
	proto.RegisterType((*GroupProfile)(nil), "com.salty.protos.GroupProfile")
	proto.RegisterType((*GroupMemberProfile)(nil), "com.salty.protos.GroupMemberProfile")
	proto.RegisterType((*Conversation)(nil), "com.salty.protos.Conversation")
	proto.RegisterType((*Message)(nil), "com.salty.protos.Message")
	proto.RegisterType((*EmptyResp)(nil), "com.salty.protos.EmptyResp")
}

func init() { proto.RegisterFile("entity.proto", fileDescriptor_cf50d946d740d100) }

var fileDescriptor_cf50d946d740d100 = []byte{
	// 1192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x36, 0xa9, 0xf3, 0xc8, 0x11, 0x98, 0x45, 0x10, 0x28, 0x41, 0xfe, 0xfc, 0x2a, 0x11, 0x14,
	0x2a, 0x10, 0xd0, 0xa8, 0x92, 0xeb, 0x04, 0x8a, 0xc9, 0x38, 0x44, 0x6d, 0xd2, 0x58, 0xca, 0x31,
	0x8a, 0x5e, 0x04, 0x6b, 0x6a, 0xad, 0xb0, 0xa1, 0xb8, 0xea, 0x72, 0xe5, 0xda, 0x0f, 0xd0, 0xeb,
	0x02, 0x7d, 0xa8, 0x02, 0xbd, 0xea, 0x9b, 0xf4, 0x15, 0x5a, 0xec, 0x2e, 0x49, 0x53, 0x96, 0x9d,
	0xb4, 0x77, 0xfc, 0xe6, 0xbc, 0x33, 0xdf, 0x8c, 0x04, 0xbb, 0x34, 0x13, 0x89, 0xb8, 0x72, 0x56,
	0x9c, 0x09, 0x86, 0xac, 0x98, 0x2d, 0x9d, 0x9c, 0xa4, 0xa5, 0x20, 0x7f, 0xfc, 0x68, 0xc1, 0xd8,
	0x22, 0xa5, 0x7b, 0x0a, 0x9e, 0xad, 0xcf, 0xf7, 0x48, 0x56, 0xe8, 0xec, 0x3f, 0x4c, 0xe8, 0x1c,
	0xf0, 0x55, 0x8c, 0xe9, 0x4f, 0xe8, 0x31, 0x74, 0xe7, 0xf4, 0x22, 0x89, 0xa9, 0x3f, 0x1f, 0x1a,
	0x23, 0x63, 0xdc, 0xc3, 0x15, 0x46, 0x43, 0xe8, 0x5c, 0x50, 0x9e, 0x27, 0x2c, 0x1b, 0x9a, 0x4a,
	0x55, 0x42, 0xf4, 0x0a, 0xba, 0x29, 0xc9, 0x16, 0x6b, 0xb2, 0xa0, 0xc3, 0xc6, 0xc8, 0x18, 0x0f,
	0x26, 0xb6, 0x73, 0xb3, 0x02, 0xa7, 0x48, 0xe1, 0x1c, 0x16, 0x96, 0xb8, 0xf2, 0x41, 0xcf, 0xc1,
	0x64, 0xf9, 0xb0, 0xa9, 0x3c, 0x9f, 0xdc, 0xed, 0x19, 0x46, 0xd8, 0x64, 0x39, 0x7a, 0x00, 0x2d,
	0xc1, 0x3e, 0xd1, 0x6c, 0xd8, 0x52, 0x55, 0x68, 0x80, 0xc6, 0xd0, 0x9c, 0x13, 0x41, 0x86, 0xed,
	0x91, 0x31, 0xee, 0x4f, 0x1e, 0x38, 0xfa, 0xbd, 0x4e, 0xf9, 0x5e, 0x67, 0x9a, 0x5d, 0x61, 0x65,
	0x61, 0x3f, 0x83, 0x6e, 0x59, 0x03, 0xea, 0x43, 0x67, 0xff, 0x9d, 0x1f, 0x78, 0x91, 0x67, 0xed,
	0x48, 0xe0, 0x05, 0x07, 0x87, 0x7e, 0xf4, 0xce, 0x32, 0xec, 0x97, 0x60, 0x86, 0x91, 0x14, 0x9d,
	0x04, 0xdf, 0x05, 0xe1, 0x69, 0xa0, 0xf5, 0xd3, 0xc0, 0xc5, 0xa1, 0xef, 0x5a, 0x06, 0xea, 0x40,
	0xc3, 0x0f, 0x23, 0xcb, 0x94, 0xd2, 0x53, 0x3f, 0x70, 0xc3, 0xd3, 0xc8, 0x6a, 0xd8, 0x67, 0xd0,
	0xd5, 0xd5, 0xe6, 0x2b, 0x84, 0xa0, 0x19, 0xb3, 0x39, 0x55, 0x7d, 0x6c, 0x61, 0xf5, 0x2d, 0x7b,
	0xb8, 0xa4, 0x79, 0x2e, 0x1b, 0x55, 0xf4, 0xb0, 0x80, 0x55, 0xfd, 0x8d, 0x2f, 0xd6, 0xff, 0xbb,
	0x09, 0xfd, 0x93, 0x9c, 0xf2, 0x63, 0xce, 0xce, 0x93, 0x94, 0xa2, 0x87, 0xd0, 0x5e, 0xe7, 0x94,
	0x57, 0x13, 0x2b, 0x10, 0x7a, 0x02, 0x3d, 0x41, 0x53, 0xba, 0xfa, 0xc8, 0xb2, 0x32, 0xdb, 0xb5,
	0x40, 0x76, 0x91, 0x2e, 0x49, 0x92, 0xaa, 0x84, 0x3d, 0xac, 0x81, 0x9c, 0x7f, 0x96, 0xc4, 0x9f,
	0x32, 0xb2, 0xa4, 0x6a, 0x1e, 0x3d, 0x5c, 0x61, 0x99, 0x87, 0x5c, 0x10, 0x41, 0x78, 0xd1, 0xf8,
	0x02, 0xa1, 0x11, 0xf4, 0xe7, 0x34, 0x8f, 0x79, 0xb2, 0x12, 0x92, 0x1b, 0x6d, 0xa5, 0xac, 0x8b,
	0xd0, 0x0b, 0x68, 0xe4, 0xf4, 0x72, 0xd8, 0x51, 0x03, 0xfe, 0x6a, 0x7b, 0xc0, 0xb5, 0xd7, 0x38,
	0x11, 0xbd, 0xc4, 0xd2, 0x5a, 0x96, 0x72, 0x96, 0x70, 0xf1, 0x71, 0x4e, 0xae, 0x86, 0xdd, 0x91,
	0x31, 0x6e, 0xe0, 0x0a, 0x4b, 0x5d, 0xca, 0x62, 0xa2, 0xf2, 0xf5, 0x74, 0x99, 0x25, 0xb6, 0xc7,
	0xd0, 0x88, 0xe8, 0xa5, 0x1c, 0x4b, 0x10, 0xce, 0x3e, 0x44, 0xde, 0xcc, 0xda, 0x41, 0x5d, 0x68,
	0x1e, 0x4d, 0x0f, 0x3d, 0xcb, 0x40, 0x00, 0xed, 0xb7, 0x9e, 0xfa, 0x36, 0xed, 0xdf, 0x0c, 0x18,
	0xec, 0xb3, 0x4c, 0x90, 0x58, 0x94, 0xbd, 0x7c, 0x0d, 0xfd, 0xf5, 0x75, 0x31, 0xaa, 0xa1, 0xfd,
	0xc9, 0xff, 0x3e, 0x5b, 0x31, 0xae, 0x7b, 0xa0, 0xd7, 0x00, 0x9c, 0x2e, 0x09, 0xff, 0xe4, 0x67,
	0xe7, 0x4c, 0x75, 0xbd, 0x3f, 0xf9, 0xff, 0xb6, 0x7f, 0x91, 0x16, 0x2b, 0x53, 0x5c, 0x73, 0xb1,
	0x7f, 0x31, 0xe0, 0xde, 0x86, 0x16, 0x3d, 0x2d, 0x43, 0x06, 0x72, 0x2a, 0x7a, 0xc6, 0x35, 0xc9,
	0xcd, 0xfe, 0x9b, 0xdb, 0xfd, 0x7f, 0x0a, 0x50, 0x0d, 0x3e, 0x1f, 0x36, 0x46, 0x0d, 0x19, 0xe1,
	0x5a, 0x22, 0x99, 0x2a, 0xc8, 0x42, 0x6e, 0xa0, 0xd4, 0xa8, 0x6f, 0xfb, 0x2f, 0x03, 0x76, 0x0f,
	0x38, 0x5b, 0xaf, 0xca, 0x97, 0x0d, 0xa1, 0xb3, 0x90, 0xb8, 0xe2, 0x59, 0x09, 0xa5, 0xbb, 0x22,
	0x8c, 0xce, 0xac, 0xbe, 0x65, 0xca, 0x98, 0x53, 0x22, 0xe8, 0x2c, 0x59, 0xea, 0xa3, 0xd0, 0xc0,
	0x35, 0x89, 0x2c, 0x9a, 0xfd, 0x9c, 0x51, 0x7e, 0xa2, 0x99, 0xab, 0xb9, 0x56, 0x17, 0xdd, 0x49,
	0xb7, 0x87, 0xd0, 0xce, 0x98, 0x48, 0x62, 0x5a, 0x30, 0xad, 0x40, 0xe8, 0x95, 0x5c, 0xad, 0xe5,
	0x19, 0xe5, 0xf9, 0xb0, 0x33, 0x6a, 0x8c, 0xfb, 0x93, 0x67, 0xb7, 0x5d, 0x12, 0xb6, 0x5e, 0x1d,
	0x29, 0xab, 0x72, 0x7a, 0xa5, 0x93, 0xfd, 0xab, 0x09, 0x68, 0x5b, 0xff, 0x99, 0x67, 0x3f, 0x80,
	0x16, 0x49, 0x13, 0x92, 0x17, 0xef, 0xd6, 0x00, 0xbd, 0x81, 0x26, 0x67, 0x69, 0x79, 0x07, 0x9d,
	0x7f, 0x53, 0x83, 0x16, 0x61, 0x96, 0x52, 0xac, 0x7c, 0x25, 0xbd, 0x7f, 0x64, 0x49, 0xa6, 0x5a,
	0xd7, 0xd4, 0xd4, 0x2f, 0xf1, 0x4d, 0x86, 0xb6, 0xfe, 0x2b, 0x43, 0xed, 0x31, 0xf4, 0xaa, 0x7c,
	0x72, 0x31, 0x82, 0x30, 0x90, 0xc7, 0xef, 0x3e, 0xdc, 0x9b, 0xba, 0x47, 0x7e, 0xe0, 0x47, 0x33,
	0x3c, 0x9d, 0x85, 0xd8, 0x32, 0xec, 0x3f, 0x9b, 0xb0, 0xbb, 0xcf, 0x32, 0x79, 0xe5, 0xd5, 0x6a,
	0xa1, 0xaf, 0x61, 0x10, 0xd7, 0x70, 0xd5, 0x92, 0x1b, 0x52, 0xf4, 0x1c, 0xee, 0xd7, 0x25, 0xb3,
	0x44, 0xa4, 0x25, 0x3b, 0xb6, 0x15, 0x92, 0x0a, 0x2b, 0xc6, 0x05, 0x27, 0x89, 0x38, 0xe1, 0xe5,
	0x3d, 0xaa, 0x8b, 0x90, 0x03, 0x68, 0x9d, 0x71, 0x4a, 0xe6, 0x47, 0xfa, 0x58, 0xee, 0xb3, 0x75,
	0x26, 0x54, 0x67, 0x5a, 0xf8, 0x16, 0x8d, 0x9c, 0x4c, 0x92, 0xcf, 0xd8, 0x4a, 0x75, 0xa7, 0x8b,
	0x35, 0x40, 0xaf, 0xe1, 0x5e, 0x4a, 0x04, 0xcd, 0x45, 0x61, 0x5b, 0xfc, 0x54, 0x3c, 0xda, 0xee,
	0x5d, 0x61, 0x80, 0x37, 0xed, 0x65, 0xd8, 0x39, 0x27, 0xe7, 0x42, 0x1d, 0xb2, 0x1e, 0xd6, 0x00,
	0xfd, 0x00, 0xd6, 0xc6, 0x9b, 0xae, 0x56, 0x54, 0xdd, 0xab, 0xc1, 0x64, 0xef, 0xd6, 0xbd, 0xaf,
	0x2c, 0x37, 0x80, 0x74, 0xc3, 0x5b, 0x81, 0x10, 0x01, 0x24, 0xe9, 0x7d, 0x9e, 0xe8, 0xe3, 0x16,
	0x09, 0x22, 0xd6, 0xb9, 0x3a, 0x79, 0x83, 0xc9, 0xb7, 0x5f, 0x08, 0x1f, 0x6c, 0x39, 0xe2, 0x5b,
	0x82, 0xd9, 0x2f, 0xc1, 0xba, 0x59, 0x48, 0x8d, 0x16, 0x7d, 0xe8, 0x1c, 0x63, 0xff, 0xfd, 0x74,
	0x26, 0x8f, 0x67, 0x0f, 0x5a, 0x07, 0x38, 0x3c, 0x39, 0xb6, 0x4c, 0xfb, 0x25, 0xa0, 0xed, 0xf8,
	0xf2, 0xba, 0x06, 0xe1, 0xcc, 0x7f, 0xfb, 0xbd, 0xb5, 0x83, 0x10, 0x0c, 0xdc, 0xf0, 0x83, 0xbc,
	0xc1, 0xae, 0x1f, 0xcd, 0x4e, 0xf0, 0x1b, 0xcb, 0xb0, 0xff, 0x6e, 0x40, 0xa7, 0xec, 0xe6, 0x13,
	0xe8, 0x15, 0xbf, 0x7d, 0xbe, 0x5b, 0xf0, 0xe8, 0x5a, 0x20, 0xb7, 0x3c, 0x67, 0x5c, 0xf8, 0x6e,
	0xc1, 0x9b, 0x02, 0x21, 0x1b, 0x76, 0x73, 0x9a, 0xcd, 0xab, 0xc3, 0xa1, 0xd9, 0xb2, 0x21, 0x93,
	0xeb, 0x23, 0x08, 0x5f, 0x50, 0x51, 0x1d, 0x96, 0x0a, 0x4b, 0x9d, 0xb4, 0x55, 0xab, 0xd5, 0xd2,
	0xab, 0x55, 0x62, 0x19, 0x9b, 0xd3, 0x98, 0x26, 0x17, 0x54, 0xeb, 0xdb, 0x4a, 0xbf, 0x21, 0x93,
	0xfe, 0x92, 0x6e, 0x4a, 0xdf, 0xd1, 0xfe, 0x25, 0x46, 0x2e, 0x40, 0x4e, 0x33, 0x51, 0x0c, 0x49,
	0x73, 0xe0, 0xd9, 0x9d, 0xec, 0x72, 0xa2, 0xca, 0x16, 0xd7, 0xfc, 0xd0, 0x31, 0x0c, 0xca, 0x8c,
	0x1b, 0xe3, 0x1e, 0xdf, 0x1d, 0x09, 0x6f, 0xd8, 0xe3, 0x1b, 0xfe, 0xf6, 0x1e, 0xc0, 0x75, 0x2e,
	0x39, 0xd1, 0xc8, 0x0b, 0x5c, 0x3f, 0x38, 0xb0, 0x76, 0xd4, 0xcf, 0xe1, 0xd4, 0x3f, 0xf4, 0xe4,
	0x3f, 0x9a, 0x2e, 0x34, 0xb1, 0x37, 0x75, 0x2d, 0xd3, 0x76, 0x60, 0xb0, 0x19, 0x12, 0xed, 0x42,
	0x17, 0x7b, 0xfb, 0x9e, 0xff, 0xde, 0x73, 0xad, 0x1d, 0x34, 0x00, 0x70, 0xc3, 0xd3, 0xe0, 0x30,
	0x9c, 0xba, 0xd2, 0xd3, 0xfe, 0x06, 0xac, 0xa2, 0x14, 0x37, 0xe1, 0x34, 0x56, 0xb7, 0xa2, 0x0b,
	0x4d, 0x99, 0x46, 0x53, 0xa8, 0xf0, 0xb5, 0x0c, 0xbb, 0x0f, 0x3d, 0x6f, 0xb9, 0x12, 0x57, 0xf2,
	0x1f, 0xd2, 0x1b, 0xf3, 0xd8, 0x38, 0x6b, 0xab, 0xb7, 0xbc, 0xf8, 0x27, 0x00, 0x00, 0xff, 0xff,
	0x53, 0xf3, 0x1b, 0x8c, 0xc1, 0x0a, 0x00, 0x00,
}
