// Code generated by protoc-gen-go. DO NOT EDIT.
// source: group.proto

package com_salty_protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateGroupReq struct {
	GroupName            string   `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
	MemberUserIdArr      []string `protobuf:"bytes,2,rep,name=memberUserIdArr,proto3" json:"memberUserIdArr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupReq) Reset()         { *m = CreateGroupReq{} }
func (m *CreateGroupReq) String() string { return proto.CompactTextString(m) }
func (*CreateGroupReq) ProtoMessage()    {}
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{0}
}

func (m *CreateGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupReq.Unmarshal(m, b)
}
func (m *CreateGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupReq.Marshal(b, m, deterministic)
}
func (m *CreateGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupReq.Merge(m, src)
}
func (m *CreateGroupReq) XXX_Size() int {
	return xxx_messageInfo_CreateGroupReq.Size(m)
}
func (m *CreateGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupReq proto.InternalMessageInfo

func (m *CreateGroupReq) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *CreateGroupReq) GetMemberUserIdArr() []string {
	if m != nil {
		return m.MemberUserIdArr
	}
	return nil
}

type CreateGroupResp struct {
	Profile              *GroupProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateGroupResp) Reset()         { *m = CreateGroupResp{} }
func (m *CreateGroupResp) String() string { return proto.CompactTextString(m) }
func (*CreateGroupResp) ProtoMessage()    {}
func (*CreateGroupResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{1}
}

func (m *CreateGroupResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupResp.Unmarshal(m, b)
}
func (m *CreateGroupResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupResp.Marshal(b, m, deterministic)
}
func (m *CreateGroupResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupResp.Merge(m, src)
}
func (m *CreateGroupResp) XXX_Size() int {
	return xxx_messageInfo_CreateGroupResp.Size(m)
}
func (m *CreateGroupResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupResp proto.InternalMessageInfo

func (m *CreateGroupResp) GetProfile() *GroupProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type JoinGroupReq struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGroupReq) Reset()         { *m = JoinGroupReq{} }
func (m *JoinGroupReq) String() string { return proto.CompactTextString(m) }
func (*JoinGroupReq) ProtoMessage()    {}
func (*JoinGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{2}
}

func (m *JoinGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGroupReq.Unmarshal(m, b)
}
func (m *JoinGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGroupReq.Marshal(b, m, deterministic)
}
func (m *JoinGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGroupReq.Merge(m, src)
}
func (m *JoinGroupReq) XXX_Size() int {
	return xxx_messageInfo_JoinGroupReq.Size(m)
}
func (m *JoinGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGroupReq proto.InternalMessageInfo

func (m *JoinGroupReq) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *JoinGroupReq) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type JoinGroupResp struct {
	Profile              *GroupProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *JoinGroupResp) Reset()         { *m = JoinGroupResp{} }
func (m *JoinGroupResp) String() string { return proto.CompactTextString(m) }
func (*JoinGroupResp) ProtoMessage()    {}
func (*JoinGroupResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{3}
}

func (m *JoinGroupResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGroupResp.Unmarshal(m, b)
}
func (m *JoinGroupResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGroupResp.Marshal(b, m, deterministic)
}
func (m *JoinGroupResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGroupResp.Merge(m, src)
}
func (m *JoinGroupResp) XXX_Size() int {
	return xxx_messageInfo_JoinGroupResp.Size(m)
}
func (m *JoinGroupResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGroupResp.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGroupResp proto.InternalMessageInfo

func (m *JoinGroupResp) GetProfile() *GroupProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type QuitGroupReq struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitGroupReq) Reset()         { *m = QuitGroupReq{} }
func (m *QuitGroupReq) String() string { return proto.CompactTextString(m) }
func (*QuitGroupReq) ProtoMessage()    {}
func (*QuitGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{4}
}

func (m *QuitGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitGroupReq.Unmarshal(m, b)
}
func (m *QuitGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitGroupReq.Marshal(b, m, deterministic)
}
func (m *QuitGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitGroupReq.Merge(m, src)
}
func (m *QuitGroupReq) XXX_Size() int {
	return xxx_messageInfo_QuitGroupReq.Size(m)
}
func (m *QuitGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_QuitGroupReq proto.InternalMessageInfo

func (m *QuitGroupReq) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type QuitGroupResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitGroupResp) Reset()         { *m = QuitGroupResp{} }
func (m *QuitGroupResp) String() string { return proto.CompactTextString(m) }
func (*QuitGroupResp) ProtoMessage()    {}
func (*QuitGroupResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{5}
}

func (m *QuitGroupResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitGroupResp.Unmarshal(m, b)
}
func (m *QuitGroupResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitGroupResp.Marshal(b, m, deterministic)
}
func (m *QuitGroupResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitGroupResp.Merge(m, src)
}
func (m *QuitGroupResp) XXX_Size() int {
	return xxx_messageInfo_QuitGroupResp.Size(m)
}
func (m *QuitGroupResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitGroupResp.DiscardUnknown(m)
}

var xxx_messageInfo_QuitGroupResp proto.InternalMessageInfo

type AddGroupMemberReq struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	MemberUserIdArr      []string `protobuf:"bytes,2,rep,name=memberUserIdArr,proto3" json:"memberUserIdArr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupMemberReq) Reset()         { *m = AddGroupMemberReq{} }
func (m *AddGroupMemberReq) String() string { return proto.CompactTextString(m) }
func (*AddGroupMemberReq) ProtoMessage()    {}
func (*AddGroupMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{6}
}

func (m *AddGroupMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupMemberReq.Unmarshal(m, b)
}
func (m *AddGroupMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupMemberReq.Marshal(b, m, deterministic)
}
func (m *AddGroupMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupMemberReq.Merge(m, src)
}
func (m *AddGroupMemberReq) XXX_Size() int {
	return xxx_messageInfo_AddGroupMemberReq.Size(m)
}
func (m *AddGroupMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupMemberReq proto.InternalMessageInfo

func (m *AddGroupMemberReq) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *AddGroupMemberReq) GetMemberUserIdArr() []string {
	if m != nil {
		return m.MemberUserIdArr
	}
	return nil
}

type AddGroupMemberResp struct {
	Profile              *GroupProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddGroupMemberResp) Reset()         { *m = AddGroupMemberResp{} }
func (m *AddGroupMemberResp) String() string { return proto.CompactTextString(m) }
func (*AddGroupMemberResp) ProtoMessage()    {}
func (*AddGroupMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{7}
}

func (m *AddGroupMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupMemberResp.Unmarshal(m, b)
}
func (m *AddGroupMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupMemberResp.Marshal(b, m, deterministic)
}
func (m *AddGroupMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupMemberResp.Merge(m, src)
}
func (m *AddGroupMemberResp) XXX_Size() int {
	return xxx_messageInfo_AddGroupMemberResp.Size(m)
}
func (m *AddGroupMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupMemberResp proto.InternalMessageInfo

func (m *AddGroupMemberResp) GetProfile() *GroupProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type KickGroupMemberReq struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	MemberUserId         string   `protobuf:"bytes,2,opt,name=memberUserId,proto3" json:"memberUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickGroupMemberReq) Reset()         { *m = KickGroupMemberReq{} }
func (m *KickGroupMemberReq) String() string { return proto.CompactTextString(m) }
func (*KickGroupMemberReq) ProtoMessage()    {}
func (*KickGroupMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{8}
}

func (m *KickGroupMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickGroupMemberReq.Unmarshal(m, b)
}
func (m *KickGroupMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickGroupMemberReq.Marshal(b, m, deterministic)
}
func (m *KickGroupMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickGroupMemberReq.Merge(m, src)
}
func (m *KickGroupMemberReq) XXX_Size() int {
	return xxx_messageInfo_KickGroupMemberReq.Size(m)
}
func (m *KickGroupMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_KickGroupMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_KickGroupMemberReq proto.InternalMessageInfo

func (m *KickGroupMemberReq) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *KickGroupMemberReq) GetMemberUserId() string {
	if m != nil {
		return m.MemberUserId
	}
	return ""
}

type KickGroupMemberResp struct {
	Profile              *GroupProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *KickGroupMemberResp) Reset()         { *m = KickGroupMemberResp{} }
func (m *KickGroupMemberResp) String() string { return proto.CompactTextString(m) }
func (*KickGroupMemberResp) ProtoMessage()    {}
func (*KickGroupMemberResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{9}
}

func (m *KickGroupMemberResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickGroupMemberResp.Unmarshal(m, b)
}
func (m *KickGroupMemberResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickGroupMemberResp.Marshal(b, m, deterministic)
}
func (m *KickGroupMemberResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickGroupMemberResp.Merge(m, src)
}
func (m *KickGroupMemberResp) XXX_Size() int {
	return xxx_messageInfo_KickGroupMemberResp.Size(m)
}
func (m *KickGroupMemberResp) XXX_DiscardUnknown() {
	xxx_messageInfo_KickGroupMemberResp.DiscardUnknown(m)
}

var xxx_messageInfo_KickGroupMemberResp proto.InternalMessageInfo

func (m *KickGroupMemberResp) GetProfile() *GroupProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type UpdateGroupNameReq struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	GroupName            string   `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupNameReq) Reset()         { *m = UpdateGroupNameReq{} }
func (m *UpdateGroupNameReq) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupNameReq) ProtoMessage()    {}
func (*UpdateGroupNameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{10}
}

func (m *UpdateGroupNameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupNameReq.Unmarshal(m, b)
}
func (m *UpdateGroupNameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupNameReq.Marshal(b, m, deterministic)
}
func (m *UpdateGroupNameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupNameReq.Merge(m, src)
}
func (m *UpdateGroupNameReq) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupNameReq.Size(m)
}
func (m *UpdateGroupNameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupNameReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupNameReq proto.InternalMessageInfo

func (m *UpdateGroupNameReq) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *UpdateGroupNameReq) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type UpdateGroupNameResp struct {
	Profile              *GroupProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateGroupNameResp) Reset()         { *m = UpdateGroupNameResp{} }
func (m *UpdateGroupNameResp) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupNameResp) ProtoMessage()    {}
func (*UpdateGroupNameResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{11}
}

func (m *UpdateGroupNameResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupNameResp.Unmarshal(m, b)
}
func (m *UpdateGroupNameResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupNameResp.Marshal(b, m, deterministic)
}
func (m *UpdateGroupNameResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupNameResp.Merge(m, src)
}
func (m *UpdateGroupNameResp) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupNameResp.Size(m)
}
func (m *UpdateGroupNameResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupNameResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupNameResp proto.InternalMessageInfo

func (m *UpdateGroupNameResp) GetProfile() *GroupProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type UpdateGroupNoticeReq struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Notice               string   `protobuf:"bytes,2,opt,name=notice,proto3" json:"notice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateGroupNoticeReq) Reset()         { *m = UpdateGroupNoticeReq{} }
func (m *UpdateGroupNoticeReq) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupNoticeReq) ProtoMessage()    {}
func (*UpdateGroupNoticeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{12}
}

func (m *UpdateGroupNoticeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupNoticeReq.Unmarshal(m, b)
}
func (m *UpdateGroupNoticeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupNoticeReq.Marshal(b, m, deterministic)
}
func (m *UpdateGroupNoticeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupNoticeReq.Merge(m, src)
}
func (m *UpdateGroupNoticeReq) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupNoticeReq.Size(m)
}
func (m *UpdateGroupNoticeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupNoticeReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupNoticeReq proto.InternalMessageInfo

func (m *UpdateGroupNoticeReq) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *UpdateGroupNoticeReq) GetNotice() string {
	if m != nil {
		return m.Notice
	}
	return ""
}

type UpdateGroupNoticeResp struct {
	Profile              *GroupProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateGroupNoticeResp) Reset()         { *m = UpdateGroupNoticeResp{} }
func (m *UpdateGroupNoticeResp) String() string { return proto.CompactTextString(m) }
func (*UpdateGroupNoticeResp) ProtoMessage()    {}
func (*UpdateGroupNoticeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{13}
}

func (m *UpdateGroupNoticeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateGroupNoticeResp.Unmarshal(m, b)
}
func (m *UpdateGroupNoticeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateGroupNoticeResp.Marshal(b, m, deterministic)
}
func (m *UpdateGroupNoticeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateGroupNoticeResp.Merge(m, src)
}
func (m *UpdateGroupNoticeResp) XXX_Size() int {
	return xxx_messageInfo_UpdateGroupNoticeResp.Size(m)
}
func (m *UpdateGroupNoticeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateGroupNoticeResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateGroupNoticeResp proto.InternalMessageInfo

func (m *UpdateGroupNoticeResp) GetProfile() *GroupProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type UpdateMemberNicknameReq struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	MemberNickname       string   `protobuf:"bytes,2,opt,name=memberNickname,proto3" json:"memberNickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMemberNicknameReq) Reset()         { *m = UpdateMemberNicknameReq{} }
func (m *UpdateMemberNicknameReq) String() string { return proto.CompactTextString(m) }
func (*UpdateMemberNicknameReq) ProtoMessage()    {}
func (*UpdateMemberNicknameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{14}
}

func (m *UpdateMemberNicknameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMemberNicknameReq.Unmarshal(m, b)
}
func (m *UpdateMemberNicknameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMemberNicknameReq.Marshal(b, m, deterministic)
}
func (m *UpdateMemberNicknameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMemberNicknameReq.Merge(m, src)
}
func (m *UpdateMemberNicknameReq) XXX_Size() int {
	return xxx_messageInfo_UpdateMemberNicknameReq.Size(m)
}
func (m *UpdateMemberNicknameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMemberNicknameReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMemberNicknameReq proto.InternalMessageInfo

func (m *UpdateMemberNicknameReq) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *UpdateMemberNicknameReq) GetMemberNickname() string {
	if m != nil {
		return m.MemberNickname
	}
	return ""
}

type UpdateMemberNicknameResp struct {
	Profile              *GroupProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateMemberNicknameResp) Reset()         { *m = UpdateMemberNicknameResp{} }
func (m *UpdateMemberNicknameResp) String() string { return proto.CompactTextString(m) }
func (*UpdateMemberNicknameResp) ProtoMessage()    {}
func (*UpdateMemberNicknameResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{15}
}

func (m *UpdateMemberNicknameResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMemberNicknameResp.Unmarshal(m, b)
}
func (m *UpdateMemberNicknameResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMemberNicknameResp.Marshal(b, m, deterministic)
}
func (m *UpdateMemberNicknameResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMemberNicknameResp.Merge(m, src)
}
func (m *UpdateMemberNicknameResp) XXX_Size() int {
	return xxx_messageInfo_UpdateMemberNicknameResp.Size(m)
}
func (m *UpdateMemberNicknameResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMemberNicknameResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMemberNicknameResp proto.InternalMessageInfo

func (m *UpdateMemberNicknameResp) GetProfile() *GroupProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateGroupReq)(nil), "com.salty.protos.createGroupReq")
	proto.RegisterType((*CreateGroupResp)(nil), "com.salty.protos.createGroupResp")
	proto.RegisterType((*JoinGroupReq)(nil), "com.salty.protos.JoinGroupReq")
	proto.RegisterType((*JoinGroupResp)(nil), "com.salty.protos.JoinGroupResp")
	proto.RegisterType((*QuitGroupReq)(nil), "com.salty.protos.QuitGroupReq")
	proto.RegisterType((*QuitGroupResp)(nil), "com.salty.protos.QuitGroupResp")
	proto.RegisterType((*AddGroupMemberReq)(nil), "com.salty.protos.AddGroupMemberReq")
	proto.RegisterType((*AddGroupMemberResp)(nil), "com.salty.protos.AddGroupMemberResp")
	proto.RegisterType((*KickGroupMemberReq)(nil), "com.salty.protos.KickGroupMemberReq")
	proto.RegisterType((*KickGroupMemberResp)(nil), "com.salty.protos.KickGroupMemberResp")
	proto.RegisterType((*UpdateGroupNameReq)(nil), "com.salty.protos.UpdateGroupNameReq")
	proto.RegisterType((*UpdateGroupNameResp)(nil), "com.salty.protos.UpdateGroupNameResp")
	proto.RegisterType((*UpdateGroupNoticeReq)(nil), "com.salty.protos.UpdateGroupNoticeReq")
	proto.RegisterType((*UpdateGroupNoticeResp)(nil), "com.salty.protos.UpdateGroupNoticeResp")
	proto.RegisterType((*UpdateMemberNicknameReq)(nil), "com.salty.protos.UpdateMemberNicknameReq")
	proto.RegisterType((*UpdateMemberNicknameResp)(nil), "com.salty.protos.UpdateMemberNicknameResp")
}

func init() { proto.RegisterFile("group.proto", fileDescriptor_e10f4c9b19ad8eee) }

var fileDescriptor_e10f4c9b19ad8eee = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xcf, 0x8f, 0xd2, 0x40,
	0x14, 0xc7, 0xa5, 0x9a, 0xdd, 0xf4, 0xd1, 0xa5, 0xee, 0xf8, 0xab, 0x12, 0x63, 0x36, 0x73, 0x30,
	0x3d, 0xf5, 0xb0, 0x5e, 0x3c, 0x8a, 0x1a, 0xb5, 0x80, 0xfc, 0xa8, 0x12, 0x4d, 0x3c, 0x95, 0x76,
	0x34, 0x13, 0x68, 0x67, 0x98, 0x16, 0x13, 0xff, 0x5f, 0xff, 0x10, 0xc3, 0xb4, 0x85, 0xb6, 0xb0,
	0x40, 0x3a, 0xc7, 0xf7, 0xe6, 0xf1, 0xc9, 0xa7, 0xc3, 0xf7, 0x0d, 0xb4, 0x7f, 0x0b, 0xb6, 0xe6,
	0x0e, 0x17, 0x2c, 0x65, 0xe8, 0x61, 0xc0, 0x22, 0x27, 0xf1, 0x97, 0xe9, 0xdf, 0xac, 0x91, 0x74,
	0x0d, 0x12, 0xa7, 0xb4, 0x28, 0xf1, 0x0f, 0xe8, 0x04, 0x82, 0xf8, 0x29, 0xf9, 0xb4, 0xf9, 0x91,
	0x47, 0x56, 0xe8, 0x05, 0xe8, 0x12, 0x30, 0xf2, 0x23, 0x62, 0xb5, 0x6e, 0x5a, 0xb6, 0xee, 0xed,
	0x1a, 0xc8, 0x06, 0x33, 0x22, 0xd1, 0x9c, 0x88, 0x59, 0x42, 0x84, 0x1b, 0xf6, 0x84, 0xb0, 0xb4,
	0x9b, 0xfb, 0xb6, 0xee, 0xd5, 0xdb, 0x78, 0x00, 0x66, 0x85, 0x9c, 0x70, 0xf4, 0x06, 0x2e, 0xb9,
	0x60, 0xbf, 0xe8, 0x32, 0x03, 0xb7, 0x6f, 0x5f, 0x3a, 0x75, 0x3d, 0x47, 0x4e, 0x4f, 0xb2, 0x29,
	0xaf, 0x18, 0xc7, 0x6f, 0xc1, 0xe8, 0x33, 0x1a, 0x6f, 0x25, 0x2d, 0xb8, 0x94, 0x4e, 0x6e, 0x98,
	0x2b, 0x16, 0x25, 0x7a, 0x0a, 0x17, 0x82, 0xf8, 0x09, 0x8b, 0x2d, 0x4d, 0x1e, 0xe4, 0x15, 0x76,
	0xe1, 0xaa, 0x44, 0x50, 0x92, 0xb1, 0xc1, 0x98, 0xae, 0x69, 0x7a, 0x5a, 0x06, 0x9b, 0x70, 0x55,
	0x9a, 0x4c, 0x38, 0xfe, 0x0e, 0xd7, 0xbd, 0x30, 0x94, 0xf5, 0x17, 0x79, 0x5f, 0xc7, 0x3f, 0xe6,
	0xfc, 0xdb, 0x1e, 0x01, 0xaa, 0x83, 0x95, 0xbe, 0xd1, 0x03, 0x34, 0xa0, 0xc1, 0xe2, 0x6c, 0x53,
	0x0c, 0x46, 0x59, 0x29, 0xbf, 0xfc, 0x4a, 0x0f, 0x8f, 0xe1, 0xd1, 0x1e, 0x53, 0x49, 0x72, 0x08,
	0x68, 0xc6, 0xc3, 0x22, 0x62, 0x9b, 0x7c, 0x1e, 0x97, 0xac, 0x44, 0x5b, 0xab, 0x45, 0x7b, 0xa3,
	0xb7, 0x47, 0x53, 0xd2, 0xfb, 0x0c, 0x8f, 0xcb, 0x40, 0x96, 0xd2, 0x80, 0x9c, 0x0c, 0x6f, 0x2c,
	0xc7, 0x8a, 0xf0, 0x66, 0x15, 0x9e, 0xc2, 0x93, 0x03, 0x24, 0x25, 0xb9, 0x9f, 0xf0, 0x2c, 0x43,
	0x66, 0xff, 0xc4, 0x88, 0x06, 0x8b, 0xf8, 0xe4, 0x05, 0xbe, 0x82, 0x4e, 0x54, 0x19, 0xcf, 0x3d,
	0x6b, 0x5d, 0xfc, 0x0d, 0xac, 0xc3, 0x70, 0x15, 0xe5, 0xdb, 0x7f, 0x0f, 0xc0, 0x90, 0x27, 0x5f,
	0x89, 0xf8, 0x43, 0x03, 0x82, 0x3e, 0x42, 0xfb, 0xfd, 0xee, 0x89, 0x41, 0xcf, 0x0f, 0x81, 0x78,
	0xe0, 0x91, 0x55, 0xb7, 0x7b, 0xd7, 0x51, 0xc2, 0xf1, 0x3d, 0xf4, 0x01, 0xf4, 0xed, 0xdb, 0xa0,
	0x44, 0xd9, 0x2e, 0x7b, 0x73, 0x8a, 0x0b, 0x9d, 0xea, 0x22, 0x37, 0x47, 0xf5, 0xc1, 0xac, 0xed,
	0x9b, 0x12, 0xab, 0xb6, 0x1c, 0xcd, 0x59, 0x43, 0xb8, 0xde, 0x4b, 0x73, 0x73, 0xda, 0xb8, 0xd8,
	0xb2, 0x6a, 0xd6, 0x1a, 0x03, 0xdf, 0x69, 0x93, 0xd6, 0xfc, 0x42, 0xb6, 0x5f, 0xff, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0x5c, 0xac, 0x0f, 0xa8, 0x4c, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GroupServiceClient is the client API for GroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GroupServiceClient interface {
	//创建群组
	CreateGroup(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//加入群组
	JoinGroup(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//退出群组
	QuitGroup(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//添加新的成员进群
	AddGroupMember(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//踢出群
	KickGroupMember(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//更新群组名字
	UpdateGroupName(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//更新群公告
	UpdateGroupNotice(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
	//更新我在群里面的群昵称
	UpdateMemberNickname(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error)
}

type groupServiceClient struct {
	cc *grpc.ClientConn
}

func NewGroupServiceClient(cc *grpc.ClientConn) GroupServiceClient {
	return &groupServiceClient{cc}
}

func (c *groupServiceClient) CreateGroup(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.GroupService/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) JoinGroup(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.GroupService/JoinGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) QuitGroup(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.GroupService/QuitGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) AddGroupMember(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.GroupService/AddGroupMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) KickGroupMember(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.GroupService/KickGroupMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) UpdateGroupName(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.GroupService/UpdateGroupName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) UpdateGroupNotice(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.GroupService/UpdateGroupNotice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) UpdateMemberNickname(ctx context.Context, in *GrpcReq, opts ...grpc.CallOption) (*GrpcResp, error) {
	out := new(GrpcResp)
	err := c.cc.Invoke(ctx, "/com.salty.protos.GroupService/UpdateMemberNickname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupServiceServer is the server API for GroupService service.
type GroupServiceServer interface {
	//创建群组
	CreateGroup(context.Context, *GrpcReq) (*GrpcResp, error)
	//加入群组
	JoinGroup(context.Context, *GrpcReq) (*GrpcResp, error)
	//退出群组
	QuitGroup(context.Context, *GrpcReq) (*GrpcResp, error)
	//添加新的成员进群
	AddGroupMember(context.Context, *GrpcReq) (*GrpcResp, error)
	//踢出群
	KickGroupMember(context.Context, *GrpcReq) (*GrpcResp, error)
	//更新群组名字
	UpdateGroupName(context.Context, *GrpcReq) (*GrpcResp, error)
	//更新群公告
	UpdateGroupNotice(context.Context, *GrpcReq) (*GrpcResp, error)
	//更新我在群里面的群昵称
	UpdateMemberNickname(context.Context, *GrpcReq) (*GrpcResp, error)
}

// UnimplementedGroupServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGroupServiceServer struct {
}

func (*UnimplementedGroupServiceServer) CreateGroup(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (*UnimplementedGroupServiceServer) JoinGroup(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinGroup not implemented")
}
func (*UnimplementedGroupServiceServer) QuitGroup(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuitGroup not implemented")
}
func (*UnimplementedGroupServiceServer) AddGroupMember(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGroupMember not implemented")
}
func (*UnimplementedGroupServiceServer) KickGroupMember(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickGroupMember not implemented")
}
func (*UnimplementedGroupServiceServer) UpdateGroupName(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroupName not implemented")
}
func (*UnimplementedGroupServiceServer) UpdateGroupNotice(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroupNotice not implemented")
}
func (*UnimplementedGroupServiceServer) UpdateMemberNickname(ctx context.Context, req *GrpcReq) (*GrpcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMemberNickname not implemented")
}

func RegisterGroupServiceServer(s *grpc.Server, srv GroupServiceServer) {
	s.RegisterService(&_GroupService_serviceDesc, srv)
}

func _GroupService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.GroupService/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).CreateGroup(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_JoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).JoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.GroupService/JoinGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).JoinGroup(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_QuitGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).QuitGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.GroupService/QuitGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).QuitGroup(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_AddGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).AddGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.GroupService/AddGroupMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).AddGroupMember(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_KickGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).KickGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.GroupService/KickGroupMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).KickGroupMember(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_UpdateGroupName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).UpdateGroupName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.GroupService/UpdateGroupName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).UpdateGroupName(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_UpdateGroupNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).UpdateGroupNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.GroupService/UpdateGroupNotice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).UpdateGroupNotice(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_UpdateMemberNickname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrpcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).UpdateMemberNickname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.salty.protos.GroupService/UpdateMemberNickname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).UpdateMemberNickname(ctx, req.(*GrpcReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GroupService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.salty.protos.GroupService",
	HandlerType: (*GroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroup",
			Handler:    _GroupService_CreateGroup_Handler,
		},
		{
			MethodName: "JoinGroup",
			Handler:    _GroupService_JoinGroup_Handler,
		},
		{
			MethodName: "QuitGroup",
			Handler:    _GroupService_QuitGroup_Handler,
		},
		{
			MethodName: "AddGroupMember",
			Handler:    _GroupService_AddGroupMember_Handler,
		},
		{
			MethodName: "KickGroupMember",
			Handler:    _GroupService_KickGroupMember_Handler,
		},
		{
			MethodName: "UpdateGroupName",
			Handler:    _GroupService_UpdateGroupName_Handler,
		},
		{
			MethodName: "UpdateGroupNotice",
			Handler:    _GroupService_UpdateGroupNotice_Handler,
		},
		{
			MethodName: "UpdateMemberNickname",
			Handler:    _GroupService_UpdateMemberNickname_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "group.proto",
}
